/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.barber.view.dialog;

import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import poly.barber.entity.Appointment;
import poly.barber.entity.Customer;
import poly.barber.entity.Employee;
import poly.barber.entity.Invoice;
import poly.barber.entity.Payment;
import poly.barber.repository.Impl.AppointmentRepositoryImpl;
import poly.barber.repository.Impl.CustomerImpl;
import poly.barber.repository.Impl.EmployeeImpl;
import poly.barber.repository.Impl.InvoiceRepositoryImpl;
import poly.barber.repository.Impl.PaymentRepositoryImpl;
import poly.barber.service.InvoiceService;
import poly.barber.util.XQuery;

/**
 *
 * @author Admin
 */
public class HistoryJdialog extends javax.swing.JDialog {

    private InvoiceService invoiceSer = new InvoiceService();
    private PaymentRepositoryImpl paymentRepo = new PaymentRepositoryImpl();
    private EmployeeImpl employeeRepo = new EmployeeImpl();
    private InvoiceRepositoryImpl invoiceRepo = new InvoiceRepositoryImpl();
    private DefaultTableModel dtm = new DefaultTableModel();
    private CustomerImpl customerRepo = new CustomerImpl();
    private AppointmentRepositoryImpl appointmentRepo = new AppointmentRepositoryImpl();

    /**
     * Creates new form HistoryJdialog
     */
    public HistoryJdialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        // Đổi ngôn ngữ JDateChooser sang tiếng Việt
        Locale localeVN = new Locale("vi", "VN");
        jdTuNgay.setLocale(localeVN);
        jdDenNgay.setLocale(localeVN);

        // Nếu muốn hiển thị định dạng ngày kiểu Việt Nam (dd/MM/yyyy)
        jdTuNgay.setDateFormatString("dd/MM/yyyy");
        jdDenNgay.setDateFormatString("dd/MM/yyyy");

        dtm = (DefaultTableModel) tblLichSu.getModel();
        loadToTable(invoiceRepo.getAll());
        loadToComboboxNhanVien(employeeRepo.getAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tabInvoiceDetail = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboNhanVien = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLoc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLichSu = new javax.swing.JTable();
        jdTuNgay = new com.toedter.calendar.JDateChooser();
        jdDenNgay = new com.toedter.calendar.JDateChooser();
        btnBoLoc = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDanhSachDV = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rdoDaThanhToan = new javax.swing.JRadioButton();
        rdoDaHuy = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtTimeCheckOut = new javax.swing.JTextField();
        txtNhanVien = new javax.swing.JTextField();
        txtTimeCheckIn = new javax.swing.JTextField();
        txtGiamGia = new javax.swing.JTextField();
        txtThanhTien = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPhuongThucThanhToan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nhân Viên");

        cboNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNhanVienActionPerformed(evt);
            }
        });

        jLabel2.setText("Từ Ngày");

        jLabel3.setText("Đến Ngày");

        btnLoc.setText("Tìm Kiếm");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        tblLichSu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Hóa Đơn", "Mã Hóa Đơn", "Nhân Viên", "Tên Khách Hàng", "SĐT", "Trạng Thái", "Thành Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLichSu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLichSuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLichSu);

        btnBoLoc.setText("Bỏ Lọc");
        btnBoLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoLocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cboNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jdTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jdDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBoLoc)
                        .addGap(18, 18, 18)
                        .addComponent(btnLoc)
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLoc)
                        .addComponent(btnBoLoc))
                    .addComponent(jdDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabInvoiceDetail.addTab("Lịch Sử Hóa Đơn", jPanel1);

        tblDanhSachDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Dịch Vụ", "Tên Dịch Vụ", "Số Lượng", "Giá", "Thành Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDanhSachDV);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mã Hóa Đơn");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tên Khách Hàng");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Số Điện Thoại");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Thời Gian Check-In");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Thời Gian Check-Out");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Giảm Giá");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Trạng Thái");

        buttonGroup1.add(rdoDaThanhToan);
        rdoDaThanhToan.setSelected(true);
        rdoDaThanhToan.setText("Đã Thanh Toán");

        buttonGroup1.add(rdoDaHuy);
        rdoDaHuy.setText("Đã Hủy");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Nhân Viên");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Thành Tiền ");

        jLabel15.setText("Phương Thức Thanh Toán ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rdoDaThanhToan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdoDaHuy))
                                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTimeCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPhuongThucThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTimeCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(rdoDaThanhToan)
                    .addComponent(rdoDaHuy)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txtTimeCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimeCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(txtNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtPhuongThucThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Dịch Vụ Đã Dùng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 459, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(409, 409, 409))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabInvoiceDetail.addTab("Chi Tiết Hóa Đơn", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabInvoiceDetail)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabInvoiceDetail)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblLichSuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLichSuMouseClicked
        if (evt.getClickCount() == 2) {
            showDetail();
        }
    }//GEN-LAST:event_tblLichSuMouseClicked

    private void cboNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNhanVienActionPerformed
        Object selectedItem = cboNhanVien.getSelectedItem();
        if (selectedItem == null) {
            return;
        }

        String selectedName = selectedItem.toString();
        List<Invoice> list;

        if (selectedName.equals("Tất Cả")) {
            list = invoiceRepo.getAll(); // Giả sử invoiceRepo là thực thể của InvoiceRepositoryImpl
        } else {
            // Gọi hàm lọc theo tên đã sửa SQL ở Bước 1
            list = invoiceRepo.getByEmployeeName(selectedName);
        }

        // Dùng hàm bạn đã viết để đổ dữ liệu lên bảng
        loadToTable(list);
    }//GEN-LAST:event_cboNhanVienActionPerformed

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        searchByDate();
    }//GEN-LAST:event_btnLocActionPerformed

    private void btnBoLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoLocActionPerformed
        loadToTable(invoiceRepo.getAll());
        cboNhanVien.setSelectedIndex(0);

        ((JTextField) jdTuNgay.getDateEditor().getUiComponent()).setText("");
        ((JTextField) jdDenNgay.getDateEditor().getUiComponent()).setText("");
    }//GEN-LAST:event_btnBoLocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoryJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoryJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoryJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoryJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HistoryJdialog dialog = new HistoryJdialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoLoc;
    private javax.swing.JButton btnLoc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboNhanVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdDenNgay;
    private com.toedter.calendar.JDateChooser jdTuNgay;
    private javax.swing.JRadioButton rdoDaHuy;
    private javax.swing.JRadioButton rdoDaThanhToan;
    private javax.swing.JTabbedPane tabInvoiceDetail;
    private javax.swing.JTable tblDanhSachDV;
    private javax.swing.JTable tblLichSu;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtNhanVien;
    private javax.swing.JTextField txtPhuongThucThanhToan;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtTimeCheckIn;
    private javax.swing.JTextField txtTimeCheckOut;
    // End of variables declaration//GEN-END:variables

    private void loadToTable(List<Invoice> all) {
        dtm.setRowCount(0);
        for (Invoice i : all) {
            String customerName = "Khách vãng lai"; // Mặc định
            String customerPhone = "";

            // CHỈ lấy thông tin nếu ID > 0 (Tránh lỗi SQL khi tìm ID 0)
            if (i.getAppointmentID() > 0) {
                Appointment appointment = appointmentRepo.getOne(i.getAppointmentID());
                if (appointment != null) {
                    Customer customer = customerRepo.getOne(appointment.getCustomerID());
                    if (customer != null) {
                        customerName = customer.getFullname();
                        customerPhone = customer.getPhone();
                    }
                }
            }

            dtm.addRow(new Object[]{
                i.getInvoiceID(),
                i.getInvoiceCode(),
                // Kiểm tra nhân viên tránh NullPointerException
                employeeRepo.getOne(i.getCreatedByEmployeeID()) != null
                ? employeeRepo.getOne(i.getCreatedByEmployeeID()).getFirstname() : "Admin",
                customerName,
                customerPhone,
                i.getStatus() == 1 ? "Đã Thanh Toán" : "Chưa Thanh Toán",
                i.getTotalAmount()
            });
        }
    }

    private void showDetail() {
        // 1. Lấy dòng đang được chọn
        int row = tblLichSu.getSelectedRow();

        if (row != -1) { // Đảm bảo có dòng được chọn
            // 2. Lấy ID hóa đơn (Giả sử ID nằm ở cột 0)
            String invoiceID = tblLichSu.getValueAt(row, 0).toString();

            // 3. Gọi hàm đổ dữ liệu chi tiết lên Tab "Chi Tiết Hóa Đơn"
            // Bạn cần viết hàm này ở Bước 3
            loadInvoiceDetail(invoiceID);

            // 4. Chuyển Tab (Chỉ số tab bắt đầu từ 0, Lịch sử là 0, Chi tiết là 1)
            tabInvoiceDetail.setSelectedIndex(1);
            fillServiceTable(invoiceID);
        }
    }

    private void loadInvoiceDetail(String invoiceID) {
        int id = Integer.parseInt(invoiceID);
        Invoice invoice = invoiceRepo.getOne(id);

        if (invoice != null) {
            txtMaHoaDon.setText(String.valueOf(invoice.getInvoiceCode()));

            //Lấy appointmentID từ invoice
            int appointmentID = invoice.getAppointmentID();
            Appointment app = appointmentRepo.getOne(appointmentID);

            if (app != null) {
                int khachHangId = app.getCustomerID();
                Customer kh = customerRepo.getOne(khachHangId);
                if (kh != null) {
                    txtTenKH.setText(kh.getFullname());
                    txtSDT.setText(kh.getPhone());
                } else {
                    txtTenKH.setText("Không có thông tin");
                    txtSDT.setText("Không có thông tin");
                }
            }

            int nvID = invoice.getCreatedByEmployeeID();
            Employee emp = employeeRepo.getOne(nvID);
            if (emp != null) {
                txtNhanVien.setText(emp.getFirstname() + " " + emp.getLastname());
            } else {
                txtNhanVien.setText("Không xác định !");
            }

            // 1. Khai báo định dạng (Dấu phẩy phân cách, không lấy số lẻ thập phân)
            java.text.DecimalFormat df = new java.text.DecimalFormat("#,###");

            // 2. Ép kiểu dữ liệu về Number và format
            double amount = invoice.getTotalAmount().doubleValue();
            txtThanhTien.setText(df.format(amount)); // Kết quả sẽ là: 800,000
            txtTimeCheckIn.setText(String.valueOf(invoice.getCheckInDateTime()));
            txtTimeCheckOut.setText(String.valueOf(invoice.getCheckOutDateTime()));
            txtGiamGia.setText(String.valueOf(invoice.getTotalDiscount()));

            //txtPhuongThucThanhToan
            Payment p = paymentRepo.getOneByInvoiceID(invoiceID);
            if (p != null) {
                // Truy vấn nhanh cái tên dựa vào ID phương thức
                String sql = "SELECT PaymentName FROM PaymentMethod WHERE PaymentMethodID = ?";
                List<Object[]> list = XQuery.getRawList(sql, p.getPaymentMethodID());

                if (!list.isEmpty()) {
                    txtPhuongThucThanhToan.setText(list.get(0)[0].toString());
                }
            } else {
                txtPhuongThucThanhToan.setText("Chưa xác định");
            }

            int trangThai = invoice.getStatus();
            if (trangThai == 1) {
                rdoDaThanhToan.setSelected(true);
            } else {
                rdoDaHuy.setSelected(true);
            }
        }

        //txt chỉ xem
        txtMaHoaDon.setEditable(false);
        txtTenKH.setEditable(false);
        txtSDT.setEditable(false);
        txtThanhTien.setEditable(false);
        txtGiamGia.setEditable(false);
        txtNhanVien.setEditable(false);
        txtThanhTien.setEditable(false);
        txtTimeCheckIn.setEditable(false);
        txtTimeCheckOut.setEditable(false);
        txtPhuongThucThanhToan.setEditable(false);
    }

    private void fillServiceTable(String invoiceID) {
        DefaultTableModel model = (DefaultTableModel) tblDanhSachDV.getModel();
        model.setRowCount(0);

        List<Object[]> list = invoiceRepo.GetDetailsByInvoiceId(invoiceID);
        int stt = 1;
        for (Object[] row : list) {
            // row[0]: ServiceName (String)
            // row[1]: Quantity (Integer)
            // row[2]: Price (BigDecimal)
            // row[3]: Total (BigDecimal)

            // Cách ép kiểu an toàn cho cả BigDecimal và Double
            double price = ((Number) row[2]).doubleValue();
            double total = ((Number) row[3]).doubleValue();

            model.addRow(new Object[]{
                stt++,
                row[0],
                row[1],
                String.format("%,.0f", price), // Định dạng tiền 50,000
                String.format("%,.0f", total)
            });
        }
    }

    private void loadToComboboxNhanVien(List<Employee> all) {
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
        dcbm = (DefaultComboBoxModel) cboNhanVien.getModel();
        dcbm.removeAllElements();
        dcbm.addElement("Tất Cả");
        for (Employee e : all) {
            dcbm.addElement(e.getFirstname() + " " + e.getLastname());
        }

    }

    private void searchByDate() {
        DefaultTableModel model = (DefaultTableModel) tblLichSu.getModel();
        model.setRowCount(0); // Xóa trắng bảng

        Date start = jdTuNgay.getDate();
        Date end = jdDenNgay.getDate();
        String empName = cboNhanVien.getSelectedItem().toString();

        if (start == null || end == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn đầy đủ ngày!");
            return;
        }
        // 2. Validate: Ngày bắt đầu không được lớn hơn ngày kết thúc
        if (start.after(end)) {
            JOptionPane.showMessageDialog(this, "Ngày bắt đầu phải nhỏ hơn hoặc bằng ngày kết thúc!",
                    "Lỗi chọn ngày", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Gọi service với 3 tham số
        List<Object[]> data = invoiceSer.findHistory(start, end, empName);

        for (Object[] row : data) {
            // row[5] là Status (int), ta đổi sang chữ cho người dùng dễ đọc
            row[5] = (int) row[5] == 1 ? "Đã thanh toán" : "Chưa thanh toán";

            // row[6] là TotalAmount, định dạng lại tiền tệ
            row[6] = String.format("%,.0f VNĐ", Double.parseDouble(row[6].toString()));

            model.addRow(row);
        }

    }

}
