/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.barber.view.dialog;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import poly.barber.entity.Invoice;
import poly.barber.repository.Impl.CustomerRepository;
import poly.barber.repository.Impl.InvoiceDetailRepository;
import poly.barber.repository.Impl.InvoiceRepositoryImpl;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;

/**
 *
 * @author DELL
 */
public class InvoiceJDialog extends javax.swing.JDialog {

    private InvoiceRepositoryImpl ir = new InvoiceRepositoryImpl();
    private DefaultTableModel dtm = new DefaultTableModel();
    private InvoiceDetailRepository idr = new InvoiceDetailRepository();
    private CustomerRepository cr = new CustomerRepository();

    private List<Invoice> listInvoice;

    /**
     * Creates new form InvoiceJDialog
     */
    public InvoiceJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);

        dtm = (DefaultTableModel) tblHoaDon.getModel();
        tblHoaDon.setAutoCreateRowSorter(true);
        tblBarber.setAutoCreateRowSorter(true);
        showTable(ir.getAll());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        lblMaHD = new javax.swing.JLabel();
        lblNgay = new javax.swing.JLabel();
        lblTenKhach = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblnguoitao = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblServiceDetails = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarber = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtSearchCustomer = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();
        btnIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 102, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOÁ ĐƠN");
        jLabel1.setOpaque(true);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DANH SÁCH HOÁ ĐƠN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tblHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã ĐL", "Mã HĐ", "Time in", "Time out", "Tổng tiền", "Giảm giá", "Trạng thái", "Nhân viên"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHoaDon);

        jButton1.setText("Thanh toán");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel2.setText("Mã HĐ");

        jLabel3.setText("Ngày");

        jLabel4.setText("Tên Khách");

        lblSDT.setText("  ");

        lblMaHD.setText("  ");

        lblNgay.setText("  ");

        lblTenKhach.setText("  ");

        jLabel9.setText("SĐT");

        jLabel11.setText("Người tạo");

        lblnguoitao.setText("  ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblNgay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSDT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMaHD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTenKhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblnguoitao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblMaHD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblNgay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTenKhach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblSDT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnguoitao)
                    .addComponent(jLabel11)))
        );

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DỊCH VỤ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tblServiceDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblServiceDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên dịch vụ", "Số lượng", "Đơn giá"
            }
        ));
        jScrollPane3.setViewportView(tblServiceDetails);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thợ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tblBarber.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Thợ", "Làm"
            }
        ));
        jScrollPane1.setViewportView(tblBarber);

        jLabel5.setText("Tìm kiếm khách hàng:");

        txtSearchCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchCustomerKeyReleased(evt);
            }
        });

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnIn.setText("In");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnLamMoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(btnLamMoi)
                    .addComponent(btnIn))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        int row = tblHoaDon.getSelectedRow();
        if (row < 0) {
            return;
        }

        // 1. Lấy InvoiceID an toàn
        Object valId = tblHoaDon.getValueAt(row, 1);
        String maHDStr = (valId == null) ? "" : valId.toString();
        // Dùng try-catch hoặc kiểm tra để tránh lỗi format số
        int maHD = -1;
        try {
            if (!maHDStr.isEmpty()) {
                maHD = Integer.parseInt(maHDStr);
            }
        } catch (NumberFormatException e) {
            System.out.println("Lỗi định dạng mã HĐ");
        }

        // 2. Lấy Ngày an toàn (SỬA LỖI DÒNG 327 TẠI ĐÂY)
        Object valNgay = tblHoaDon.getValueAt(row, 2);
        String ngayStr = (valNgay == null) ? "" : valNgay.toString();

        // 3. Lấy Object từ list an toàn
        int modelRow = tblHoaDon.convertRowIndexToModel(row);

        // Kiểm tra index để tránh lỗi văng khỏi danh sách (IndexOutOfBounds)
        if (modelRow >= 0 && modelRow < listInvoice.size()) {
            Invoice selectedInv = listInvoice.get(modelRow);

            // Đổ dữ liệu lên Label
            lblMaHD.setText(maHDStr);
            lblNgay.setText(ngayStr); // Đã an toàn

            // Check null người tạo
            String infoNguoiTao = (selectedInv != null) ? selectedInv.getEmployeeName() : "Không rõ";
            lblnguoitao.setText(infoNguoiTao);
        }

        // 4. Lấy thông tin khách và load bảng dịch vụ
        if (maHD != -1) {
            String[] info = cr.getCustomerInfoByInvoiceId(maHD);
            if (info != null && info.length >= 2) {
                lblTenKhach.setText(info[0]);
                lblSDT.setText(info[1]);
            } else {
                lblTenKhach.setText("Khách vãng lai");
                lblSDT.setText("Không có");
            }

            loadServiceTable(maHD);
            loadBarberTable(maHD);
        }
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Kiểm tra xem người dùng đã chọn dòng nào trên table chưa

        int row = tblHoaDon.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một hóa đơn từ danh sách để thanh toán!");
            return;
        }

        Object value = tblHoaDon.getValueAt(row, 2);
// Dùng String.valueOf để biến null thành chuỗi "null", tránh lỗi khi so sánh .equals("")
        if (value == null || String.valueOf(value).trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lịch chưa kết thúc, không thể thanh toán!");
            return;
        }

        // 2. Kiểm tra trạng thái hóa đơn (Tránh thanh toán lại hóa đơn đã xong)
        // Giả sử cột Trạng thái là cột số 6
        String trangThai = tblHoaDon.getValueAt(row, 6).toString();
        if (trangThai.equals("Đã thanh toán")) {
            JOptionPane.showMessageDialog(this, "Hóa đơn này đã được thanh toán trước đó.");
            return;
        }

        // 3. Lấy các thông tin cần thiết từ dòng đã chọn
        String maHD = tblHoaDon.getValueAt(row, 1).toString();
        String tongTien = tblHoaDon.getValueAt(row, 4).toString();

        // 4. Khởi tạo PaymentJDialog và truyền dữ liệu
        // 'this' là Frame/Dialog cha, 'true' để khóa màn hình cũ cho đến khi xong việc
        PaymentJDialog paymentWin = new PaymentJDialog(null, true);

        // Gọi phương thức nhận dữ liệu bên PaymentJDialog (Xem bước 2)
        paymentWin.setPaymentData(maHD, tongTien);

        // Hiển thị Dialog
        paymentWin.setVisible(true);

        // 5. SAU KHI THANH TOÁN XONG (Dialog đóng) -> Cập nhật lại bảng
        showTable(ir.getAll());

        lblMaHD.setText(" ");
        lblNgay.setText(" ");
        lblTenKhach.setText(" ");
        lblSDT.setText(" ");
        lblnguoitao.setText(" ");
        ((DefaultTableModel) tblServiceDetails.getModel()).setRowCount(0);
        ((DefaultTableModel) tblBarber.getModel()).setRowCount(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSearchCustomerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchCustomerKeyReleased
        String searchName = txtSearchCustomer.getText().trim();

        // 1. Gọi Repository để lấy danh sách kết quả
        List<Invoice> result;
        if (searchName.isEmpty()) {
            result = ir.getAll(); // Nếu trống thì hiện tất cả
        } else {
            result = ir.searchByCustomerName(searchName);
        }

        // 2. Đổ dữ liệu vào bảng
        showTable(result);

        // 3. Xóa trắng các thông tin chi tiết đang hiển thị bên trên
        // để tránh người dùng hiểu lầm đó là chi tiết của hóa đơn mới tìm thấy
        clearDetails();
    }//GEN-LAST:event_txtSearchCustomerKeyReleased

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        showTable(ir.getAll());

        txtSearchCustomer.setText("");

        clearDetails();

    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        int row = tblHoaDon.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hóa đơn cần in!");
            return;
        }

        Object value = tblHoaDon.getValueAt(row, 2);
        if (value == null || String.valueOf(value).trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lịch chưa hoàn thành, không được in!");
            return;
        }

        // Sử dụng tên class đầy đủ để tránh lỗi Document của Swing
        com.itextpdf.text.Document document = new com.itextpdf.text.Document();
        try {
            String maHD = tblHoaDon.getValueAt(row, 1).toString();
            String fileName = "HoaDon_5AE_" + maHD + ".pdf";
            PdfWriter.getInstance(document, new FileOutputStream(fileName));
            document.open();

            // Cấu hình Font tiếng Việt
            BaseFont bf = BaseFont.createFont("C:\\Windows\\Fonts\\Arial.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
            Font fontTitle = new Font(bf, 18, Font.BOLD);
            Font fontBold = new Font(bf, 12, Font.BOLD);
            Font fontNormal = new Font(bf, 12, Font.NORMAL);

            // Nội dung hóa đơn
            Paragraph title = new Paragraph("5AE BARBER CÚT CÚT", fontTitle);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            document.add(new Paragraph("Mã hóa đơn: " + maHD, fontNormal));
            document.add(new Paragraph("Khách hàng: " + lblTenKhach.getText(), fontNormal));
            document.add(new Paragraph("Ngày tạo: " + lblNgay.getText(), fontNormal));
            document.add(new Paragraph("Nhân viên: " + lblnguoitao.getText(), fontNormal));
            document.add(new Paragraph("------------------------------------------------------------------"));

            // Tạo bảng dịch vụ
            PdfPTable table = new PdfPTable(3);
            table.setWidthPercentage(100);
            table.setSpacingBefore(10f);

            table.addCell(new PdfPCell(new Paragraph("Dịch vụ", fontBold)));
            table.addCell(new PdfPCell(new Paragraph("Số lượng", fontBold)));
            table.addCell(new PdfPCell(new Paragraph("Đơn giá", fontBold)));

            for (int i = 0; i < tblServiceDetails.getRowCount(); i++) {
                table.addCell(new Paragraph(tblServiceDetails.getValueAt(i, 0).toString(), fontNormal));
                table.addCell(new Paragraph(tblServiceDetails.getValueAt(i, 1).toString(), fontNormal));
                table.addCell(new Paragraph(tblServiceDetails.getValueAt(i, 2).toString(), fontNormal));
            }
            document.add(table);

            document.add(new Paragraph("\nTổng tiền thanh toán: " + tblHoaDon.getValueAt(row, 4).toString() + " VNĐ", fontBold));
            document.add(new Paragraph("\nCảm ơn quý khách đã tin tưởng 5AE Barber!", fontNormal));

            document.close();

            // Mở file ngay lập tức
            File pdfFile = new File(fileName);
            if (pdfFile.exists()) {
                Desktop.getDesktop().open(pdfFile);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi in hóa đơn: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InvoiceJDialog dialog = new InvoiceJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblMaHD;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTenKhach;
    private javax.swing.JLabel lblnguoitao;
    private javax.swing.JTable tblBarber;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblServiceDetails;
    private javax.swing.JTextField txtSearchCustomer;
    // End of variables declaration//GEN-END:variables

    private void showTable(List<Invoice> all) {
        this.listInvoice = all;

        dtm.setRowCount(0);
        for (Invoice i : all) {
            String trangThaiTxt = (i.getStatus() == 2) ? "Đã thanh toán" : "Chưa thanh toán";

            dtm.addRow(new Object[]{
                i.getAppointmentID(),
                i.getInvoiceID(),
                i.getCheckInDateTime(),
                i.getCheckOutDateTime(),
                String.format("%,.0f", i.getTotalAmount()),
                String.format("%,.0f", i.getTotalDiscount()),
                trangThaiTxt,
                i.getEmployeeName()
            });
        }
    }

    private void loadServiceTable(int parseInt) {

        DefaultTableModel dtmServices = (DefaultTableModel) tblServiceDetails.getModel();
        dtmServices.setRowCount(0);

        try {
            // Sử dụng tham số invoiceID truyền vào thay vì maHD
            List<Object[]> details = idr.getServiceDetails(parseInt);

            if (details != null) {
                for (Object[] row : details) {
                    dtmServices.addRow(new Object[]{
                        row[0], // Tên dịch vụ (ServiceName)
                        row[1], // Số lượng (Quantity)
                        String.format("%,.0f", row[3]) // Tổng tiền (Total)
                    });
                }
            }
        } catch (Exception e) {
            System.out.println("Lỗi load bảng dịch vụ: " + e.getMessage());
        }
    }

    private void loadBarberTable(int invoiceId) {
        DefaultTableModel dtmBarber = (DefaultTableModel) tblBarber.getModel();
        dtmBarber.setRowCount(0);

        try {
            List<Object[]> list = idr.getBarbersByInvoice(invoiceId);
            if (list != null) {
                for (Object[] row : list) {
                    dtmBarber.addRow(row);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void clearDetails() {
        lblMaHD.setText(" ");
        lblNgay.setText(" ");
        lblTenKhach.setText(" ");
        lblSDT.setText(" ");
        lblnguoitao.setText(" ");
        ((DefaultTableModel) tblServiceDetails.getModel()).setRowCount(0);
        ((DefaultTableModel) tblBarber.getModel()).setRowCount(0);
        DefaultTableModel dtmBarbers = (DefaultTableModel) tblBarber.getModel();
        dtmBarbers.setRowCount(0);
    }

    public void exportToPDF(int invoiceId) {
        // Chỉ định rõ ràng là Document của iText để tránh xung đột với Swing
        com.itextpdf.text.Document document = new com.itextpdf.text.Document();
        try {
            String path = "HoaDon_" + invoiceId + ".pdf";
            PdfWriter.getInstance(document, new FileOutputStream(path));
            document.open();

            // Cấu hình Font (Đảm bảo file Arial.ttf có tồn tại trong máy)
            BaseFont bf = BaseFont.createFont("C:\\Windows\\Fonts\\Arial.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
            com.itextpdf.text.Font fontTitle = new com.itextpdf.text.Font(bf, 18, com.itextpdf.text.Font.BOLD);
            com.itextpdf.text.Font fontBold = new com.itextpdf.text.Font(bf, 12, com.itextpdf.text.Font.BOLD);
            com.itextpdf.text.Font fontNormal = new com.itextpdf.text.Font(bf, 12, com.itextpdf.text.Font.NORMAL);

            // ... các đoạn Paragraph và Table giữ nguyên như cũ ...
            // Lưu ý: Paragraph cũng nên dùng của iText
            document.close();
            JOptionPane.showMessageDialog(this, "Xuất hóa đơn thành công!");
            java.awt.Desktop.getDesktop().open(new java.io.File(path));
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }
    }
}
