/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.barber.view.dialog;

import poly.barber.entity.Account;
import poly.barber.repository.Impl.loginRepository;
import javax.swing.JOptionPane;
import poly.barber.service.AccountService;
import poly.barber.view.Barber5AEJFrame;
import java.io.*;
import java.util.Properties;
import poly.barber.util.Session;

/**
 *
 * @author Os
 */
public class LoginDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginDialog.class.getName());
    AccountService service = new AccountService();
    
    /**
     * Creates new form LoginDialog
     */
    Barber5AEJFrame parent;

    public LoginDialog(Barber5AEJFrame parent) {
        super(parent, true); // modal
        this.parent = parent;
        initComponents();
        setLocationRelativeTo(parent);
        
//        txtname.setText("longvt");
//        psw.setText("123");
//        loadAccount();
    }
    private boolean loginSuccess = false;

    public boolean isLoginSuccess() {
        return loginSuccess;
    }
    private Account account;

    public Account getAccount() {
        return account;
    }

    public void saveAccount(String user, String pass, String role) {
        try {
            File file = new File("accounts.txt");

            if (!file.exists()) {
                file.createNewFile();
            }

            BufferedReader br = new BufferedReader(new FileReader(file));
            String line;
            while ((line = br.readLine()) != null) {
                if (line.equals(user + "|" + pass + "|" + role)) {
                    br.close();
                    return;
                }
            }
            br.close();

            BufferedWriter bw = new BufferedWriter(new FileWriter(file, true));
            bw.write(user + "|" + pass + "|" + role);
            bw.newLine();
            bw.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public java.util.List<String> getSavedAccounts() {
        java.util.List<String> list = new java.util.ArrayList<>();

        try {
            File file = new File("accounts.txt");
            if (!file.exists()) {
                return list;
            }

            BufferedReader br = new BufferedReader(new FileReader(file));
            String line;

            while ((line = br.readLine()) != null) {
                list.add(line);
            }

            br.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        return list;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnlil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        psw = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btnLoginIn = new javax.swing.JButton();
        checkboxlil = new javax.swing.JCheckBox();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setPreferredSize(new java.awt.Dimension(400, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 100));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 51));
        jLabel5.setText("Chào mừng quay  trở lại");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel13.add(jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 100));

        btnlil.setBackground(new java.awt.Color(0, 102, 153));
        btnlil.setForeground(new java.awt.Color(255, 255, 255));
        btnlil.setText("Đăng nhập với toàn khoản hiện có");
        btnlil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlilActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setText("Tên Đăng Nhập");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtname)
                    .addComponent(jLabel2)
                    .addComponent(btnlil, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnlil, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel13.add(jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 200));

        jButton2.setBackground(new java.awt.Color(0, 102, 153));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Kết thúc");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        psw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setText("Mật Khẩu");

        btnLoginIn.setBackground(new java.awt.Color(0, 102, 153));
        btnLoginIn.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginIn.setText("Đăng nhập");
        btnLoginIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginInActionPerformed(evt);
            }
        });

        checkboxlil.setText("ghi nhớ tài khoản");
        checkboxlil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxlilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLoginIn)
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addGap(41, 41, 41))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkboxlil)
                    .addComponent(psw, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(psw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkboxlil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoginIn)
                    .addComponent(jButton2))
                .addGap(36, 36, 36))
        );

        jPanel13.add(jPanel4);

        getContentPane().add(jPanel13, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnLoginInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginInActionPerformed
        // TODO add your handling code here:
String user = txtname.getText().trim();
    String pass = new String(psw.getPassword()).trim();

    // ✅ validate trước
    if (user.isEmpty() || pass.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Không được để trống!");
        return;
    }

    try {
        // ✅ gọi DB 1 lần duy nhất
        Account acc = service.login(user, pass);

        // ✅ GÁN SESSION Ở ĐÂY
        Session.user = acc;

        // ✅ lưu nếu tick
        if (checkboxlil.isSelected()) {
            saveAccount(user, pass, String.valueOf(acc.getRole()));
        }

        JOptionPane.showMessageDialog(this,
                "Đăng nhập thành công!\nRole: " + acc.getRole()
        );

        loginSuccess = true;
        this.account = acc;

        dispose();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnLoginInActionPerformed

    private void pswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswActionPerformed

    private void checkboxlilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxlilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxlilActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void btnlilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlilActionPerformed
        // TODO add your handling code here:
        java.util.List<String> accounts = getSavedAccounts();

        if (accounts.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa có tài khoản nào được lưu!");
            return;
        }

        String selected = (String) JOptionPane.showInputDialog(
                this,
                "Chọn tài khoản:",
                "Danh sách tài khoản",
                JOptionPane.QUESTION_MESSAGE,
                null,
                accounts.toArray(),
                accounts.get(0)
        );

        if (selected != null) {
            String[] parts = selected.split("\\|");
            txtname.setText(parts[0]);
            psw.setText(parts[1]);
        }
    }//GEN-LAST:event_btnlilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//
//  java.awt.EventQueue.invokeLater(() -> {
//
//        // 🌟 Splash
//        SplashDialog splash = new SplashDialog(null, true);
//        splash.setVisible(true);
//
//        // 🧱 Main (chưa show)
//        Barber5AEJFrame main = new Barber5AEJFrame();
//
//        // 🔐 Login
//        LoginDialog login = new LoginDialog(main);
//        login.setVisible(true);
//
//        if (login.isLoginSuccess()) {
//            main.setUser(login.getAccount());
//            main.setVisible(true);
//        } else {
//            System.exit(0);
//        }
//
//    });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoginIn;
    private javax.swing.JButton btnlil;
    private javax.swing.JCheckBox checkboxlil;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField psw;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
