/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.barber.view.dialog;

import java.math.BigDecimal;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import poly.barber.entity.Invoice;
import poly.barber.entity.PaymentMethod;
import poly.barber.repository.Impl.InvoiceDetailRepository;
import poly.barber.repository.Impl.InvoiceRepositoryImpl;
import poly.barber.repository.Impl.PaymentMethodRepository;

import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.io.File;
import java.awt.Desktop;
/**
 *
 * @author DELL
 */
public class PaymentJDialog extends javax.swing.JDialog {

    private PaymentMethodRepository pmr = new PaymentMethodRepository();
    private DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
    private DefaultTableModel dtm = new DefaultTableModel();
    private InvoiceDetailRepository idr = new InvoiceDetailRepository();

    public void setPaymentData(String maHD, String tongTien) {
        // 1. Hiển thị thông tin lên các ô nhập
        txtMaHD.setText(maHD);
        lblTongTien1.setText(tongTien);
        lblThanhTien.setText(tongTien);

        // 2. Lấy Model của bảng và xóa trắng dữ liệu cũ (nếu có)
        DefaultTableModel dtmServices = (DefaultTableModel) tblServiceDetails.getModel();
        dtmServices.setRowCount(0);

        try {
            // 3. Gọi Repository để lấy danh sách dịch vụ theo Mã HĐ
            // Lưu ý: Đảm bảo idr đã được khai báo ở đầu Class
            List<Object[]> details = idr.getServiceDetails(Integer.parseInt(maHD));

            if (details != null) {
                for (Object[] row : details) {
                    // Thêm từng dòng vào bảng: Tên dịch vụ, Số lượng, Thành tiền
                    dtmServices.addRow(new Object[]{
                        row[0], // ServiceName
                        row[1], // Quantity
                        String.format("%,.0f", row[3]) // Total (Thành tiền)
                    });
                }
            }
        } catch (Exception e) {
            System.out.println("Lỗi load bảng dịch vụ: " + e.getMessage());
        }

        // 4. Reset các ô tính tiền
        txtGiamGia.setText("0");
        txtTienKhachDua.setText("");
        lblTienTraLai.setText("0");
    }

    /**
     * Creates new form PaymentJDialog
     */
    public PaymentJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        btnThanhToanIn.setEnabled(false);
        dcbm = (DefaultComboBoxModel) cboPaymentMethods.getModel();
        showComboBox(pmr.getAll());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblServiceDetails = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        lblTong = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTienKhachDua = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblTra = new javax.swing.JLabel();
        cboPaymentMethods = new javax.swing.JComboBox<>();
        lblTienTraLai = new javax.swing.JLabel();
        lblThanhTien = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTong1 = new javax.swing.JLabel();
        lblTongTien1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtGiamGia = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnThanhToanIn = new javax.swing.JButton();
        btnIn = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 102, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THANH TOÁN HOÁ ĐƠN");
        jLabel1.setOpaque(true);

        tblServiceDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên dịch vụ", "Số lượng", "Đơn giá"
            }
        ));
        jScrollPane2.setViewportView(tblServiceDetails);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết thanh toán"));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setText("Mã HĐ:");

        txtMaHD.setEditable(false);

        lblTong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTong.setForeground(new java.awt.Color(51, 51, 51));
        lblTong.setText("TỔNG TIỀN:");

        jLabel5.setText("Phương thức:");

        txtTienKhachDua.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTienKhachDua.setMaximumSize(new java.awt.Dimension(64, 22));
        txtTienKhachDua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyTyped(evt);
            }
        });

        jLabel6.setText("Tiền khách đưa:");

        lblTra.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTra.setForeground(new java.awt.Color(0, 204, 0));
        lblTra.setText("TIỀN TRẢ LẠI:");

        cboPaymentMethods.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboPaymentMethods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPaymentMethodsActionPerformed(evt);
            }
        });

        lblTienTraLai.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTienTraLai.setForeground(new java.awt.Color(0, 204, 0));
        lblTienTraLai.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTienTraLai.setText("             ");

        lblThanhTien.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblThanhTien.setForeground(new java.awt.Color(255, 0, 51));
        lblThanhTien.setText("thanh tiền");

        jLabel3.setText("Giảm giá:");

        lblTong1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTong1.setForeground(new java.awt.Color(255, 0, 51));
        lblTong1.setText("THÀNH TIỀN:");

        lblTongTien1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTongTien1.setForeground(new java.awt.Color(51, 51, 51));
        lblTongTien1.setText("TỔNG TIỀN:");

        txtGiamGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGiamGiaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaHD))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboPaymentMethods, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTienKhachDua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTong, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTongTien1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTong1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblThanhTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTienTraLai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTongTien1)
                    .addComponent(lblTong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTong1)
                    .addComponent(lblThanhTien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboPaymentMethods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTienKhachDua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTienTraLai)
                    .addComponent(lblTra))
                .addGap(14, 14, 14))
        );

        btnThanhToanIn.setBackground(new java.awt.Color(0, 51, 255));
        btnThanhToanIn.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToanIn.setText("Thanh toán");
        btnThanhToanIn.setPreferredSize(new java.awt.Dimension(420, 32));
        btnThanhToanIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanInActionPerformed(evt);
            }
        });
        jPanel2.add(btnThanhToanIn);

        btnIn.setText("In");
        btnIn.setPreferredSize(new java.awt.Dimension(190, 32));
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });
        jPanel2.add(btnIn);

        btnHuy.setText("Huỷ");
        btnHuy.setPreferredSize(new java.awt.Dimension(190, 32));
        jPanel2.add(btnHuy);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTienKhachDuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyReleased
        try {
            if (lblThanhTien.getText().isEmpty()) {
                return;
            }

            double tongTien = Double.parseDouble(lblThanhTien.getText().replace(",", ""));
            double khachDua = Double.parseDouble(txtTienKhachDua.getText());
            double conThieu = tongTien - khachDua;

            if (conThieu > 0) {
                lblTienTraLai.setForeground(java.awt.Color.RED);
                lblTra.setForeground(java.awt.Color.RED);
                lblTra.setText("Con Thiếu: ");
                lblTienTraLai.setText(String.format("%,.0f", conThieu));
                btnThanhToanIn.setEnabled(false); // Khóa nút thanh toán
            } else {
                lblTienTraLai.setForeground(new java.awt.Color(0, 153, 51)); // Màu xanh
                lblTra.setForeground(new java.awt.Color(0, 153, 51));
                lblTra.setText("Tiền trả lại: ");
                lblTienTraLai.setText(String.format("%,.0f", Math.abs(conThieu)));
                btnThanhToanIn.setEnabled(true); // Mở khóa nút thanh toán
            }
        } catch (NumberFormatException e) {
            lblTienTraLai.setText("0");
            btnThanhToanIn.setEnabled(false);
        }
    }//GEN-LAST:event_txtTienKhachDuaKeyReleased

    private void btnThanhToanInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanInActionPerformed
        try {
            String maHD = txtMaHD.getText();
            if (maHD.isEmpty()) {
                return;
            }

            double tongGoc = Double.parseDouble(lblTongTien1.getText().replace(",", ""));
            double thanhTien = Double.parseDouble(lblThanhTien.getText().replace(",", ""));
            double tienGiam = tongGoc - thanhTien;

            Invoice inv = new Invoice();
            inv.setInvoiceID(Integer.parseInt(maHD));
            inv.setTotalAmount(BigDecimal.valueOf(thanhTien)); // Cập nhật tiền sau giảm
            inv.setTotalDiscount(BigDecimal.valueOf(tienGiam)); // Cập nhật số tiền được giảm
            inv.setStatus(2); // Đã thanh toán

            InvoiceRepositoryImpl ir = new InvoiceRepositoryImpl();
            ir.update(inv);

            JOptionPane.showMessageDialog(this, "Thanh toán thành công!");
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi thanh toán: " + e.getMessage());
            e.printStackTrace();
        }    }//GEN-LAST:event_btnThanhToanInActionPerformed

    private void cboPaymentMethodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPaymentMethodsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPaymentMethodsActionPerformed

    private void txtGiamGiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiamGiaKeyReleased
        try {
            // 1. Lấy tổng tiền gốc từ label (loại bỏ dấu phẩy nếu có)
            double tongTienGoc = Double.parseDouble(lblTongTien1.getText().replace(",", ""));

            // 2. Lấy % giảm giá từ ô nhập (nếu trống thì coi như 0%)
            String rGiamGia = txtGiamGia.getText().trim();
            double phanTram = rGiamGia.isEmpty() ? 0 : Double.parseDouble(rGiamGia);

            // Giới hạn không cho giảm quá 100%
            if (phanTram > 100) {
                phanTram = 100;
            }
            if (phanTram < 0) {
                phanTram = 0;
            }

            // 3. Tính toán: Thành tiền = Tổng gốc - (Tổng gốc * % / 100)
            double tienGiam = tongTienGoc * (phanTram / 100);
            double thanhTien = tongTienGoc - tienGiam;

            // 4. Hiển thị kết quả lên Label Thành tiền (định dạng số nguyên)
            lblThanhTien.setText(String.format("%.0f", thanhTien));

        } catch (NumberFormatException e) {
            // Nếu người dùng nhập chữ, mặc định Thành tiền = Tổng tiền gốc
            lblThanhTien.setText(lblTongTien1.getText());
        }
    }//GEN-LAST:event_txtGiamGiaKeyReleased

    private void txtTienKhachDuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyTyped
        if (txtTienKhachDua.getText().length() >= 12 || !Character.isDigit(evt.getKeyChar())) {
            evt.consume(); // Hủy sự kiện phím, không cho hiện chữ lên ô text
        }
    }//GEN-LAST:event_txtTienKhachDuaKeyTyped

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        String maHD = txtMaHD.getText();
    if (maHD.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Không có thông tin hóa đơn để in!");
        return;
    }

    // Khởi tạo Document của iText (dùng đường dẫn đầy đủ để tránh xung đột)
    com.itextpdf.text.Document document = new com.itextpdf.text.Document();
    
    try {
        String fileName = "HoaDon_ThanhToan_" + maHD + ".pdf";
        PdfWriter.getInstance(document, new FileOutputStream(fileName));
        document.open();

        // 1. Cấu hình Font tiếng Việt (Arial có sẵn trên Windows)
        BaseFont bf = BaseFont.createFont("C:\\Windows\\Fonts\\Arial.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
        Font fontTitle = new Font(bf, 18, Font.BOLD);
        Font fontBold = new Font(bf, 12, Font.BOLD);
        Font fontNormal = new Font(bf, 12, Font.NORMAL);

        // 2. Tiêu đề cửa hàng
        Paragraph title = new Paragraph("5AE BARBER CUT CUT", fontTitle);
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);
        document.add(new Paragraph("Địa chỉ: Hà Đông, Hà Nội", fontNormal));
        document.add(new Paragraph("Mã hóa đơn: " + maHD, fontNormal));
        document.add(new Paragraph("------------------------------------------------------------------"));

        // 3. Bảng dịch vụ (Lấy từ tblServiceDetails của Khánh)
        PdfPTable table = new PdfPTable(3);
        table.setWidthPercentage(100);
        table.setSpacingBefore(10f);
        
        // Header bảng
        table.addCell(new PdfPCell(new Paragraph("Dịch vụ", fontBold)));
        table.addCell(new PdfPCell(new Paragraph("Số lượng", fontBold)));
        table.addCell(new PdfPCell(new Paragraph("Thành tiền", fontBold)));

        // Duyệt bảng tblServiceDetails
        for (int i = 0; i < tblServiceDetails.getRowCount(); i++) {
            table.addCell(new Paragraph(tblServiceDetails.getValueAt(i, 0).toString(), fontNormal));
            table.addCell(new Paragraph(tblServiceDetails.getValueAt(i, 1).toString(), fontNormal));
            table.addCell(new Paragraph(tblServiceDetails.getValueAt(i, 2).toString(), fontNormal));
        }
        document.add(table);

        // 4. Phần tính toán tiền
        document.add(new Paragraph(" "));
        document.add(new Paragraph("Tổng tiền gốc: " + lblTongTien1.getText() + " VNĐ", fontNormal));
        document.add(new Paragraph("Giảm giá: " + txtGiamGia.getText() + "%", fontNormal));
        
        Paragraph totalPay = new Paragraph("THÀNH TIỀN: " + lblThanhTien.getText() + " VNĐ", fontBold);
        totalPay.setAlignment(Element.ALIGN_RIGHT);
        document.add(totalPay);

        document.add(new Paragraph("------------------------------------------------------------------"));
        document.add(new Paragraph("Tiền khách đưa: " + txtTienKhachDua.getText() + " VNĐ", fontNormal));
        document.add(new Paragraph("Tiền trả lại: " + lblTienTraLai.getText() + " VNĐ", fontNormal));
        
        document.add(new Paragraph("\nCảm ơn quý khách! Hẹn gặp lại tại 5AE Barber!", fontNormal));

        document.close();

        // 5. Tự động mở file PDF sau khi xuất
        File file = new File(fileName);
        if (file.exists()) {
            Desktop.getDesktop().open(file);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi in hóa đơn: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PaymentJDialog dialog = new PaymentJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnThanhToanIn;
    private javax.swing.JComboBox<String> cboPaymentMethods;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblThanhTien;
    private javax.swing.JLabel lblTienTraLai;
    private javax.swing.JLabel lblTong;
    private javax.swing.JLabel lblTong1;
    private javax.swing.JLabel lblTongTien1;
    private javax.swing.JLabel lblTra;
    private javax.swing.JTable tblServiceDetails;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtTienKhachDua;
    // End of variables declaration//GEN-END:variables

    private void showComboBox(List<PaymentMethod> all) {
        dcbm.removeAllElements();
        for (PaymentMethod p : all) {
            dcbm.addElement(p.getPaymentName());
        }
    }
}
