/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.barber.view.Dialog;

import java.util.Collections;
import java.util.List;
import static java.util.random.RandomGeneratorFactory.all;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import poly.barber.entity.Service;
import poly.barber.entity.ServiceCategory;
import poly.barber.repository.Impl.ServiceCategoryRepository;
import poly.barber.repository.ServiceRepository;

/**
 *
 * @author DELL
 */
public class ServiceJDialog extends javax.swing.JDialog {

    private ServiceCategoryRepository scr = new ServiceCategoryRepository();
    private ServiceRepository sr = new ServiceRepository();
    private DefaultTableModel dtm = new DefaultTableModel();
    private DefaultComboBoxModel dcbm = new DefaultComboBoxModel();

    private List<Service> listGlobal = new java.util.ArrayList<>();
    private List<ServiceCategory> listGlobal2 = new java.util.ArrayList<>();

    /**
     * Creates new form ServiceJDialog
     */
    public ServiceJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);

        dcbm = (DefaultComboBoxModel) cboLoai.getModel();
        showTable(sr.getAll());
        showComBoBox(scr.getAll());
        reloadCboLocLoai();

        showTableCategory(scr.getAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        cboLoai = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        cboLocLoai = new javax.swing.JComboBox<>();
        btnLoc = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblService = new javax.swing.JTable();
        btnClear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMa1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTen1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblServiceCategory = new javax.swing.JTable();
        btnThem1 = new javax.swing.JButton();
        btnSua1 = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnClear2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin dịch vụ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel3.setToolTipText("Thông tin dịch vụ");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Mã");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Tên");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Giá");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Thời gian");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Loại");

        txtMa.setEditable(false);

        txtGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaActionPerformed(evt);
            }
        });

        cboLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLoaiItemStateChanged(evt);
            }
        });
        cboLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTime)
                    .addComponent(txtGia)
                    .addComponent(txtTen)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(269, 269, 269))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        cboLocLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLocLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLocLoaiActionPerformed(evt);
            }
        });

        btnLoc.setText("Lọc");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        jLabel7.setText("Loại");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách dịch vụ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        tblService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên", "Giá", "Thời gian", "Loại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblService.setMaximumSize(new java.awt.Dimension(2147, 125));
        tblService.setRowHeight(25);
        tblService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServiceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblService);
        if (tblService.getColumnModel().getColumnCount() > 0) {
            tblService.getColumnModel().getColumn(0).setMinWidth(100);
            tblService.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblService.getColumnModel().getColumn(0).setMaxWidth(100);
            tblService.getColumnModel().getColumn(2).setMinWidth(150);
            tblService.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblService.getColumnModel().getColumn(2).setMaxWidth(150);
            tblService.getColumnModel().getColumn(3).setMinWidth(150);
            tblService.getColumnModel().getColumn(3).setPreferredWidth(150);
            tblService.getColumnModel().getColumn(3).setMaxWidth(150);
        }

        btnClear.setText("Làm mới");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(btnThem)
                        .addGap(12, 12, 12)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear)
                        .addGap(169, 169, 169)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cboLocLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoc)
                        .addGap(0, 188, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnClear, btnLoc, btnSua, btnThem});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(jLabel7)
                    .addComponent(btnLoc)
                    .addComponent(cboLocLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Dịch vụ", jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin loại dịch vụ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Mã");

        txtMa1.setEditable(false);
        txtMa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMa1ActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Tên");

        txtTen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTen1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMa1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(txtTen1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel8});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtMa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách loại", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        tblServiceCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã", "Tên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblServiceCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblServiceCategory.setMaximumSize(new java.awt.Dimension(100, 100));
        tblServiceCategory.setRowHeight(25);
        tblServiceCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServiceCategoryMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblServiceCategory);
        if (tblServiceCategory.getColumnModel().getColumnCount() > 0) {
            tblServiceCategory.getColumnModel().getColumn(0).setMinWidth(200);
            tblServiceCategory.getColumnModel().getColumn(0).setMaxWidth(200);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnThem1.setText("Thêm");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        btnSua1.setText("Sửa");
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnClear2.setText("Làm mới");
        btnClear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(btnThem1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnClear2, btnSua1, btnThem1, btnXoa});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem1)
                    .addComponent(btnSua1)
                    .addComponent(btnXoa)
                    .addComponent(btnClear2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Loại dịch vụ", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServiceMouseClicked
        int index = tblService.getSelectedRow();
        if (index >= 0) {
            detailSp(listGlobal, index); // Sử dụng list đang hiển thị thay vì sr.getAll()
        }
    }//GEN-LAST:event_tblServiceMouseClicked

    private void cboLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiActionPerformed

    }//GEN-LAST:event_cboLoaiActionPerformed

    private void cboLoaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLoaiItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLoaiItemStateChanged

    private void txtGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        txtMa.setText("");
        if (checkValidate()) {
            try {
                Service s = getForm();
                sr.add(s);
                javax.swing.JOptionPane.showMessageDialog(this, "Thêm thành công!");
                showTable(sr.getAll());
                clearForm();
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Lỗi thêm mới!");
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (checkValidate()) {
            try {
                Service s = getForm();
                if (s.getServiceID() == 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 dịch vụ từ bảng để sửa!");
                    return;
                }

                sr.update(s);
                javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật thành công!");

                // Load lại dữ liệu mới nhất
                showTable(sr.getAll());
                clearForm();
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Lỗi cập nhật: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        Object selectedItem = cboLocLoai.getSelectedItem();

        if (selectedItem == null) {
            return;
        }

        // Nếu người dùng chọn "Tất cả" (là String)
        if (selectedItem instanceof String && selectedItem.equals("Tất cả")) {
            showTable(sr.getAll()); // Hiển thị toàn bộ danh sách
        } // Nếu người dùng chọn một loại cụ thể (là ServiceCategory)
        else if (selectedItem instanceof ServiceCategory) {
            ServiceCategory sc = (ServiceCategory) selectedItem;
            List<Service> filteredList = sr.getByType(sc.getServiceCategoryID());
            showTable(filteredList);

            if (filteredList.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Không có dịch vụ nào thuộc loại này.");
            }
        }
    }//GEN-LAST:event_btnLocActionPerformed

    private void cboLocLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLocLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLocLoaiActionPerformed

    private void txtMa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMa1ActionPerformed

    private void txtTen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTen1ActionPerformed

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        txtMa1.setText("");
        if (checkValidateCategory()) {
            try {
                ServiceCategory sc = getFormCategory();
                scr.add(sc);

                javax.swing.JOptionPane.showMessageDialog(this, "Thêm thành công!");
                showTableCategory(scr.getAll());
                clearFormCategory();
                showComBoBox(scr.getAll());
                reloadCboLocLoai();
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Lỗi thêm!");
            }
        }
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        if (txtMa1.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn loại để sửa!");
            return;
        }

        if (checkValidateCategory()) {
            try {
                ServiceCategory sc = getFormCategory();
                scr.update(sc);

                javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                showTableCategory(scr.getAll());
                clearFormCategory();
                showComBoBox(scr.getAll());
                reloadCboLocLoai();
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Lỗi cập nhật!");
            }
        }

    }//GEN-LAST:event_btnSua1ActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (txtMa1.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn loại để xoá!");
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc muốn xoá không?",
                "Xác nhận",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                int id = Integer.parseInt(txtMa1.getText().trim());
                scr.delete(id);

                javax.swing.JOptionPane.showMessageDialog(this, "Xoá thành công!");
                showTableCategory(scr.getAll());
                clearFormCategory();
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Không thể xoá! Có thể đang được sử dụng.");
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnClear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear2ActionPerformed
        clearFormCategory();
    }//GEN-LAST:event_btnClear2ActionPerformed

    private void tblServiceCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServiceCategoryMouseClicked
        int index = tblServiceCategory.getSelectedRow();
        if (index >= 0) {
            detailCategory(listGlobal2, index);
        }
    }//GEN-LAST:event_tblServiceCategoryMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ServiceJDialog dialog = new ServiceJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClear2;
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboLoai;
    private javax.swing.JComboBox<String> cboLocLoai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblService;
    private javax.swing.JTable tblServiceCategory;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtMa1;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTen1;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables

    private void showTable(List<Service> all) {
//        Collections.sort(all, (s1, s2) -> Integer.compare(s1.getServiceID(), s2.getServiceID()));
        DefaultTableModel dtm = (DefaultTableModel) tblService.getModel();
        java.text.DecimalFormat df = new java.text.DecimalFormat("#,###");
        dtm.setRowCount(0);
        this.listGlobal = all;

        List<ServiceCategory> listCategories = scr.getAll();

        for (Service s : all) {
            String formattedPrice = (s.getPrice() != null) ? df.format(s.getPrice()) + " VNĐ" : "0 VNĐ";

            int totalMinutes = s.getDuration();
            String timeDisplay = "";

            if (totalMinutes >= 60) {
                int hours = totalMinutes / 60;
                int mins = totalMinutes % 60;

                if (mins > 0) {
                    timeDisplay = hours + " giờ " + mins + " phút";
                } else {
                    timeDisplay = hours + " giờ";
                }
            } else {
                timeDisplay = totalMinutes + " phút";
            }

            String categoryName = "Không xác định";
            for (ServiceCategory sc : listCategories) {
                if (sc.getServiceCategoryID() == s.getServiceCategoryID()) {
                    categoryName = sc.getServiceCategoryName();
                    break;
                }
            }

            dtm.addRow(new Object[]{
                s.getServiceID(),
                s.getServiceName(),
                formattedPrice,
                timeDisplay,
                categoryName
            });
        }
    }

    private void showComBoBox(List<ServiceCategory> all) {
        dcbm.removeAllElements();
        for (ServiceCategory sc : all) {
            dcbm.addElement(sc);
        }
    }

    private void detailSp(List<Service> all, int index) {
        Service s = all.get(index);
        txtMa.setText(s.getServiceID() + "");
        txtTen.setText(s.getServiceName());

        txtGia.setText(s.getPrice().toPlainString());
        txtTime.setText(s.getDuration() + "");

        for (int i = 0; i < cboLoai.getItemCount(); i++) {
            Object item = cboLoai.getItemAt(i);

            if (item instanceof ServiceCategory) {
                ServiceCategory sc = (ServiceCategory) item;
                if (sc.getServiceCategoryID() == s.getServiceCategoryID()) {
                    cboLoai.setSelectedIndex(i);
                    break;
                }
            }
        }
    }

    private Service getForm() {
        Service s = new Service();
        String ma = txtMa.getText().trim();
        if (!ma.isEmpty()) {
            s.setServiceID(Integer.parseInt(ma));
        }

        s.setServiceName(txtTen.getText().trim());

        String giaStr = txtGia.getText().trim();
        s.setPrice(new java.math.BigDecimal(giaStr.isEmpty() ? "0" : giaStr));

        String timeStr = txtTime.getText().trim();
        s.setDuration(timeStr.isEmpty() ? 0 : Integer.parseInt(timeStr));

        ServiceCategory selectedCat = (ServiceCategory) cboLoai.getSelectedItem();
        if (selectedCat != null) {
            s.setServiceCategoryID(selectedCat.getServiceCategoryID());
        }
        return s;
    }

    private boolean checkValidate() {
        String ten = txtTen.getText().trim();
        String giaStr = txtGia.getText().trim();
        String thoiGianStr = txtTime.getText().trim();
        String maStr = txtMa.getText().trim();

        // 1. Kiểm tra trống
        if (ten.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Tên dịch vụ không được để trống!");
            txtTen.requestFocus();
            return false;
        }

        if (giaStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Giá không được để trống!");
            txtGia.requestFocus();
            return false;
        }

        // 2. Kiểm tra định dạng số cho Giá
        try {
            java.math.BigDecimal gia = new java.math.BigDecimal(giaStr);
            if (gia.compareTo(java.math.BigDecimal.ZERO) < 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Giá không được là số âm!");
                return false;
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Giá phải là số hợp lệ!");
            return false;
        }

        // 3. Kiểm tra định dạng số cho Thời gian
        try {
            int time = Integer.parseInt(thoiGianStr);
            if (time <= 0) {
                throw new Exception();
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Thời gian phải là số nguyên dương!");
            return false;
        }

        // 4. Kiểm tra trùng tên (Logic quan trọng)
        Service sCheckTen = sr.getByName(ten);

        if (sCheckTen != null) {
            // Nếu tìm thấy tên này trong DB, ta phải xác định đang "Thêm" hay "Sửa"
            // Cách tốt nhất: Nếu bạn đang bấm nút THÊM, thì tuyệt đối không được trùng

            // Giả sử ta kiểm tra nếu txtMa đang hiển thị ID của chính thằng trùng đó
            String maForm = txtMa.getText().trim();

            // Nếu txtMa trống (thêm mới chuẩn) HOẶC bạn đang bấm nút Thêm nhưng Form lại có ID
            // Cách an toàn: Trong nút THÊM, hãy coi như mọi trường hợp tìm thấy sCheckTen đều là lỗi
            if (maForm.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Tên dịch vụ đã tồn tại!");
                return false;
            } else {
                // Nếu có ID trên Form, chỉ cho phép đi tiếp nếu ID đó TRÙNG với ID của tên vừa tìm thấy (nghĩa là không sửa tên)
                int idTrenForm = Integer.parseInt(maForm);
                if (sCheckTen.getServiceID() != idTrenForm) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Tên này đã tồn tại ở một mã dịch vụ khác!");
                    return false;
                }
            }
        }
        return true;
    }

    private void clearForm() {
        txtMa.setText("");
        txtTen.setText("");
        txtGia.setText("");
        txtTime.setText("");
        cboLoai.setSelectedItem(null);;

//        if (cboLoai.getItemCount() > 0) {
//            cboLoai.setSelectedItem(0);
//        }
//        tblService.clearSelection();
    }

    private void reloadCboLocLoai() {
        List<ServiceCategory> list = scr.getAll();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLocLoai.getModel();

        model.removeAllElements();
        model.addElement("Tất cả");

        for (ServiceCategory sc : list) {
            model.addElement(sc);
        }

        cboLocLoai.setSelectedIndex(0);
    }

    private void showTableCategory(List<ServiceCategory> all) {
//        Collections.sort(all, (c1, c2) -> Integer.compare(c1.getServiceCategoryID(), c2.getServiceCategoryID()));
        DefaultTableModel dtm = (DefaultTableModel) tblServiceCategory.getModel();
        dtm.setRowCount(0);
        this.listGlobal2 = all;

        List<ServiceCategory> listCategories = scr.getAll();

        for (ServiceCategory s : listCategories) {
            dtm.addRow(new Object[]{
                s.getServiceCategoryID(),
                s.getServiceCategoryName()
            });
        }
    }

    private void detailCategory(List<ServiceCategory> all, int index) {
        ServiceCategory s = all.get(index);
        txtMa1.setText(s.getServiceCategoryID() + "");
        txtTen1.setText(s.getServiceCategoryName());
    }

    private ServiceCategory getFormCategory() {
        ServiceCategory s = new ServiceCategory();
        String ma = txtMa1.getText().trim();
        if (!ma.isEmpty()) {
            s.setServiceCategoryID(Integer.parseInt(ma));
        }
        s.setServiceCategoryName(txtTen1.getText().trim());
        return s;
    }

    private boolean checkValidateCategory() {
        String ten = txtTen1.getText().trim();
        String maStr = txtMa1.getText().trim();

        if (ten.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Tên dịch vụ không được để trống!");
            txtTen1.requestFocus();
            return false;
        }

        ServiceCategory sCheck = scr.getByName(ten);

        if (sCheck != null) {
            if (maStr.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Tên dịch vụ đã tồn tại!");
                return false;
            } else {
                int idForm = Integer.parseInt(maStr);

                if (sCheck.getServiceCategoryID() != idForm) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Tên dịch vụ đã tồn tại ở bản ghi khác!");
                    return false;
                }
            }
        }
        return true;
    }

    private void clearFormCategory() {
        txtMa1.setText("");
        txtTen1.setText("");
    }

}
