/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.barber.view.dialog;

import java.awt.Color;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.CellStyle;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import poly.barber.repository.Impl.StatisticalRepositoryImpl;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Admin
 */
public class StatisticalJdialog2 extends javax.swing.JDialog {

    private StatisticalRepositoryImpl statRepo = new StatisticalRepositoryImpl();

    /**
     * Creates new form StatisticalJdialog2
     */
    public StatisticalJdialog2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        loadDefaultChart();
        loadDefaultServiceChart();
        loadDefaultEmployeeChart();
        displaySummary();
        settingCalendar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedNhanVien = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jpnChartLeft = new javax.swing.JPanel();
        jpnChartRight = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTongQuan = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jdTuNgay = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jdDenNgay = new com.toedter.calendar.JDateChooser();
        btnReset = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnExportExcel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDoanhThuThang = new javax.swing.JTextField();
        txtDoanhThuTuan = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jdTuNgay1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jdDenNgay1 = new com.toedter.calendar.JDateChooser();
        btnReset1 = new javax.swing.JButton();
        btnSearch1 = new javax.swing.JButton();
        btnExportExcel1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jpnChartLeft1 = new javax.swing.JPanel();
        jpnChartRight1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jdTuNgay2 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jdDenNgay2 = new com.toedter.calendar.JDateChooser();
        btnReset2 = new javax.swing.JButton();
        btnSearch2 = new javax.swing.JButton();
        btnExportExcel2 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jpnChartLeft2 = new javax.swing.JPanel();
        jpnChartRight2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel4.setMaximumSize(new java.awt.Dimension(1210, 350));
        jPanel4.setPreferredSize(new java.awt.Dimension(1210, 350));
        jPanel4.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jpnChartLeft.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jpnChartLeftLayout = new javax.swing.GroupLayout(jpnChartLeft);
        jpnChartLeft.setLayout(jpnChartLeftLayout);
        jpnChartLeftLayout.setHorizontalGroup(
            jpnChartLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        jpnChartLeftLayout.setVerticalGroup(
            jpnChartLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        jPanel4.add(jpnChartLeft);

        jpnChartRight.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jpnChartRightLayout = new javax.swing.GroupLayout(jpnChartRight);
        jpnChartRight.setLayout(jpnChartRightLayout);
        jpnChartRightLayout.setHorizontalGroup(
            jpnChartRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        jpnChartRightLayout.setVerticalGroup(
            jpnChartRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        jPanel4.add(jpnChartRight);

        tblTongQuan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ngày ", "Lượng Khách", "Doanh Thu"
            }
        ));
        jScrollPane1.setViewportView(tblTongQuan);

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Từ Ngày");

        jLabel2.setText("Đến Ngày");

        btnReset.setText("Làm Mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSearch.setText("Tìm Kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnExportExcel.setText("Xuất Excel");
        btnExportExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jdTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jdDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addGap(18, 18, 18)
                .addComponent(btnExportExcel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReset)
                        .addComponent(btnSearch)
                        .addComponent(btnExportExcel))
                    .addComponent(jdDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jdTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addGap(12, 12, 12))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 51));
        jLabel7.setText("Doanh Thu Tháng Hiện Tại");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 0));
        jLabel8.setText("Doanh Thu 7 Ngày Vừa Qua");

        txtDoanhThuThang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtDoanhThuTuan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1470, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDoanhThuThang))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDoanhThuTuan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDoanhThuThang, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(txtDoanhThuTuan)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
        );

        jTabbedNhanVien.addTab("Tổng Quan", jPanel1);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Từ Ngày");

        jLabel4.setText("Đến Ngày");

        btnReset1.setText("Làm Mới");
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset1ActionPerformed(evt);
            }
        });

        btnSearch1.setText("Tìm Kiếm");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });

        btnExportExcel1.setText("Xuất Excel");
        btnExportExcel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportExcel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jdTuNgay1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jdDenNgay1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReset1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch1)
                .addGap(18, 18, 18)
                .addComponent(btnExportExcel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReset1)
                        .addComponent(btnSearch1)
                        .addComponent(btnExportExcel1))
                    .addComponent(jdDenNgay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jdTuNgay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(12, 12, 12))
        );

        jPanel7.setMaximumSize(new java.awt.Dimension(1210, 350));
        jPanel7.setPreferredSize(new java.awt.Dimension(1210, 350));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jpnChartLeft1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tỷ lệ dịch vụ khách chọn"));

        javax.swing.GroupLayout jpnChartLeft1Layout = new javax.swing.GroupLayout(jpnChartLeft1);
        jpnChartLeft1.setLayout(jpnChartLeft1Layout);
        jpnChartLeft1Layout.setHorizontalGroup(
            jpnChartLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        jpnChartLeft1Layout.setVerticalGroup(
            jpnChartLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        jPanel7.add(jpnChartLeft1);

        jpnChartRight1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tần suất sử dụng"));

        javax.swing.GroupLayout jpnChartRight1Layout = new javax.swing.GroupLayout(jpnChartRight1);
        jpnChartRight1.setLayout(jpnChartRight1Layout);
        jpnChartRight1Layout.setHorizontalGroup(
            jpnChartRight1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnChartRight1Layout.setVerticalGroup(
            jpnChartRight1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.add(jpnChartRight1);

        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên dịch vụ", "Số lượt sử dụng", "Tổng doanh thu ", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDichVu);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1470, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedNhanVien.addTab("Dịch Vụ", jPanel2);

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Từ Ngày");

        jLabel6.setText("Đến Ngày");

        btnReset2.setText("Làm Mới");
        btnReset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset2ActionPerformed(evt);
            }
        });

        btnSearch2.setText("Tìm Kiếm");
        btnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch2ActionPerformed(evt);
            }
        });

        btnExportExcel2.setText("Xuất Excel");
        btnExportExcel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportExcel2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jdTuNgay2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jdDenNgay2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReset2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch2)
                .addGap(18, 18, 18)
                .addComponent(btnExportExcel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReset2)
                        .addComponent(btnSearch2)
                        .addComponent(btnExportExcel2))
                    .addComponent(jdDenNgay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jdTuNgay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(12, 12, 12))
        );

        jPanel10.setMaximumSize(new java.awt.Dimension(1210, 350));
        jPanel10.setPreferredSize(new java.awt.Dimension(1210, 350));
        jPanel10.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jpnChartLeft2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jpnChartLeft2Layout = new javax.swing.GroupLayout(jpnChartLeft2);
        jpnChartLeft2.setLayout(jpnChartLeft2Layout);
        jpnChartLeft2Layout.setHorizontalGroup(
            jpnChartLeft2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        jpnChartLeft2Layout.setVerticalGroup(
            jpnChartLeft2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        jPanel10.add(jpnChartLeft2);

        jpnChartRight2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jpnChartRight2Layout = new javax.swing.GroupLayout(jpnChartRight2);
        jpnChartRight2.setLayout(jpnChartRight2Layout);
        jpnChartRight2Layout.setHorizontalGroup(
            jpnChartRight2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        jpnChartRight2Layout.setVerticalGroup(
            jpnChartRight2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        jPanel10.add(jpnChartRight2);

        jScrollPane3.setBorder(null);

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên dịch vụ", "Chức Vụ", "Số lượt sử dụng", "Tổng doanh thu ", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblNhanVien);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 1470, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedNhanVien.addTab("Nhân Viên", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedNhanVien)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if (isValidDate()) {
            searchByDate(); // Chỉ chạy khi ngày hợp lệ
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        resetFrom();
        displaySummary();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnExportExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportExcelActionPerformed
        // Bước duy nhất: Kiểm tra bảng có dòng nào không
        if (tblTongQuan.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Hiện tại không có dữ liệu trên bảng để xuất Excel!");
            return;
        }
        exportToExcel(tblTongQuan, "Thong_Ke_Tong_Quan");

    }//GEN-LAST:event_btnExportExcelActionPerformed

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset1ActionPerformed
        jdTuNgay1.setDate(null);
        jdDenNgay1.setDate(null);
        loadDefaultServiceChart();
        JOptionPane.showMessageDialog(this, "Đã làm mới dữ liệu dịch vụ");
    }//GEN-LAST:event_btnReset1ActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        if (isValidDate1()) {
            searchByDateSer(); // Chỉ chạy khi ngày hợp lệ
        }
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void btnExportExcel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportExcel1ActionPerformed

        if (tblDichVu.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Hiện tại không có dữ liệu trên bảng để xuất Excel!");
            return;
        }
        exportToExcel(tblDichVu, "Thong_Ke_Dich_Vu");
    }//GEN-LAST:event_btnExportExcel1ActionPerformed

    private void btnReset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset2ActionPerformed
        jdTuNgay2.setDate(null);
        jdDenNgay2.setDate(null);
        loadDefaultEmployeeChart();
        JOptionPane.showMessageDialog(this, "Đã làm mới dữ liệu dịch vụ");
    }//GEN-LAST:event_btnReset2ActionPerformed

    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2ActionPerformed
        if (isValidDate2()) {
            searchByDataEmp();
        }
    }//GEN-LAST:event_btnSearch2ActionPerformed

    private void btnExportExcel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportExcel2ActionPerformed
        // Bước duy nhất: Kiểm tra bảng có dòng nào không
        if (tblNhanVien.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Hiện tại không có dữ liệu trên bảng để xuất Excel!");
            return;
        }
        exportToExcel(tblNhanVien, "Thong_Ke_Nhan_Vien");
    }//GEN-LAST:event_btnExportExcel2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatisticalJdialog2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatisticalJdialog2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatisticalJdialog2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatisticalJdialog2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StatisticalJdialog2 dialog = new StatisticalJdialog2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportExcel;
    private javax.swing.JButton btnExportExcel1;
    private javax.swing.JButton btnExportExcel2;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnReset2;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnSearch2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedNhanVien;
    private com.toedter.calendar.JDateChooser jdDenNgay;
    private com.toedter.calendar.JDateChooser jdDenNgay1;
    private com.toedter.calendar.JDateChooser jdDenNgay2;
    private com.toedter.calendar.JDateChooser jdTuNgay;
    private com.toedter.calendar.JDateChooser jdTuNgay1;
    private com.toedter.calendar.JDateChooser jdTuNgay2;
    private javax.swing.JPanel jpnChartLeft;
    private javax.swing.JPanel jpnChartLeft1;
    private javax.swing.JPanel jpnChartLeft2;
    private javax.swing.JPanel jpnChartRight;
    private javax.swing.JPanel jpnChartRight1;
    private javax.swing.JPanel jpnChartRight2;
    private javax.swing.JTable tblDichVu;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTable tblTongQuan;
    private javax.swing.JTextField txtDoanhThuThang;
    private javax.swing.JTextField txtDoanhThuTuan;
    // End of variables declaration//GEN-END:variables

    public void loadDefaultChart() {
        DefaultTableModel model = (DefaultTableModel) tblTongQuan.getModel();
        model.setRowCount(0);

        DefaultCategoryDataset revenueDataset = new DefaultCategoryDataset();
        DefaultCategoryDataset customerDataset = new DefaultCategoryDataset();

        try {
            List<Object[]> data = statRepo.getDailySummaryLast8Days();

            for (Object[] row : data) {
                String fullDate = row[0].toString();
                model.addRow(row);

                String shortDate = fullDate.substring(0, 5);
                double khach = Double.parseDouble(row[1].toString());
                double doanhThu = Double.parseDouble(row[2].toString());

                revenueDataset.addValue(doanhThu, "Doanh thu", shortDate);
                customerDataset.addValue(khach, "Lượng khách", shortDate);
            }

            // 1. Tạo biểu đồ Doanh thu
            JFreeChart barChart = ChartFactory.createBarChart(
                    "THỐNG KÊ DOANH THU 7 NGÀY GẦN NHẤT", "Ngày", "Số tiền (VNĐ)",
                    revenueDataset, PlotOrientation.VERTICAL, false, true, false
            );

            // --- CHỈNH HIỂN THỊ SỐ CHO BIỂU ĐỒ DOANH THU ---
            org.jfree.chart.plot.CategoryPlot plotRev = barChart.getCategoryPlot();
            org.jfree.chart.renderer.category.BarRenderer rendererRev = (org.jfree.chart.renderer.category.BarRenderer) plotRev.getRenderer();
            rendererRev.setDefaultItemLabelsVisible(true); // Hiện nhãn
            rendererRev.setDefaultItemLabelGenerator(new org.jfree.chart.labels.StandardCategoryItemLabelGenerator(
                    "{2}", new java.text.DecimalFormat("#,###"))); // Định dạng số tiền có dấu phẩy
            plotRev.getRangeAxis().setUpperMargin(0.2); // Nới rộng 20% khoảng cách phía trên để hiện số không bị mất

            // 2. Tạo biểu đồ Lượng khách
            JFreeChart customerChart = ChartFactory.createBarChart(
                    "THỐNG KÊ LƯỢNG KHÁCH 7 NGÀY GẦN NHẤT", "Ngày", "Số người",
                    customerDataset, PlotOrientation.VERTICAL, false, true, false
            );

            // --- CHỈNH HIỂN THỊ SỐ CHO BIỂU ĐỒ LƯỢNG KHÁCH ---
            org.jfree.chart.plot.CategoryPlot plotCust = customerChart.getCategoryPlot();
            org.jfree.chart.renderer.category.BarRenderer rendererCust = (org.jfree.chart.renderer.category.BarRenderer) plotCust.getRenderer();
            rendererCust.setDefaultItemLabelsVisible(true); // Hiện nhãn
            rendererCust.setDefaultItemLabelGenerator(new org.jfree.chart.labels.StandardCategoryItemLabelGenerator(
                    "{2}", new java.text.DecimalFormat("0"))); // Định dạng số nguyên cho lượng khách
            plotCust.getRangeAxis().setUpperMargin(0.2); // Nới rộng khoảng cách phía trên

            // 3. Định dạng màu sắc
            formatChart(barChart, new java.awt.Color(70, 130, 180));
            formatChart(customerChart, new java.awt.Color(46, 204, 113));

            // 4. Hiển thị lên Panel
            displayChartInPanel(jpnChartLeft, barChart);
            displayChartInPanel(jpnChartRight, customerChart);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void formatChart(JFreeChart chart, Color color) {
        CategoryPlot plot = chart.getCategoryPlot();
        plot.setBackgroundPaint(Color.WHITE);
        plot.setRangeGridlinePaint(Color.LIGHT_GRAY);

        // Định dạng thanh biểu đồ
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setSeriesPaint(0, color);
        renderer.setMaximumBarWidth(0.1);

        // Giúp nhãn trục hoành không bị đè lên nhau nếu có nhiều ngày
        CategoryAxis domainAxis = plot.getDomainAxis();
        domainAxis.setCategoryLabelPositions(CategoryLabelPositions.STANDARD); // Để thẳng dd/MM cho gọn
    }

    private void displayChartInPanel(javax.swing.JPanel panel, JFreeChart chart) {
        // Khởi tạo ChartPanel với các tham số khóa tương tác:
        // ChartPanel(chart, properties, save, print, zoom, tooltips)
        ChartPanel chartPanel = new ChartPanel(chart, false, false, false, false, false);

        // Tắt Menu chuột phải (Popup Menu)
        chartPanel.setPopupMenu(null);

        // Tắt khả năng Zoom (phóng to/thu nhỏ bằng chuột)
        chartPanel.setDomainZoomable(false);
        chartPanel.setRangeZoomable(false);

        panel.removeAll();
        panel.setLayout(new java.awt.BorderLayout());
        panel.add(chartPanel, java.awt.BorderLayout.CENTER);
        panel.validate();
    }

    private void resetFrom() {
        // 1. Xóa trắng 2 ô JDateChooser
        jdTuNgay.setDate(null);
        jdDenNgay.setDate(null);

        // 2. Gọi lại hàm hiển thị mặc định (8 ngày gần nhất)
        // Giả sử hàm cũ của bạn tên là loadDefaultChart() hoặc init()
        loadDefaultChart();

        JOptionPane.showMessageDialog(this, "Đã làm mới dữ liệu thống kê");
    }

    private void searchByDate() {
        java.util.Date tuNgay = jdTuNgay.getDate();
        java.util.Date denNgay = jdDenNgay.getDate();

        List<Object[]> data = statRepo.getStatisticalByDate(tuNgay, denNgay);

        if (data.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Không có dữ liệu trong khoảng thời gian này.");
            return;
        }

        SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat chartFormat = new SimpleDateFormat("dd/MM");

        DefaultTableModel model = (DefaultTableModel) tblTongQuan.getModel();
        model.setRowCount(0);
        DefaultCategoryDataset revenueDataset = new DefaultCategoryDataset();
        DefaultCategoryDataset customerDataset = new DefaultCategoryDataset();

        for (Object[] row : data) {
            model.addRow(row);

            String fullDate = row[0].toString();
            String shortDate = fullDate;
            try {
                shortDate = chartFormat.format(inputFormat.parse(fullDate));
            } catch (Exception e) {
                if (fullDate.length() >= 5) {
                    shortDate = fullDate.substring(0, 5);
                }
            }

            double khach = Double.parseDouble(row[1].toString());
            double doanhThu = Double.parseDouble(row[2].toString());

            revenueDataset.addValue(doanhThu, "Doanh thu", shortDate);
            customerDataset.addValue(khach, "Lượng khách", shortDate);
        }

        // 2. Vẽ lại biểu đồ
        JFreeChart barChart = ChartFactory.createBarChart("DOANH THU", "Ngày", "VNĐ", revenueDataset);
        JFreeChart customerChart = ChartFactory.createBarChart("LƯỢNG KHÁCH", "Ngày", "Số lượng", customerDataset);

        // --- PHẦN BỔ SUNG: HIỂN THỊ SỐ TRÊN CỘT DOANH THU ---
        org.jfree.chart.plot.CategoryPlot plotRev = barChart.getCategoryPlot();
        org.jfree.chart.renderer.category.BarRenderer renRev = (org.jfree.chart.renderer.category.BarRenderer) plotRev.getRenderer();
        renRev.setDefaultItemLabelsVisible(true);
        renRev.setDefaultItemLabelGenerator(new org.jfree.chart.labels.StandardCategoryItemLabelGenerator(
                "{2}", new java.text.DecimalFormat("#,###")));
        plotRev.getRangeAxis().setUpperMargin(0.2); // Nới rộng đỉnh biểu đồ 20%

        // --- PHẦN BỔ SUNG: HIỂN THỊ SỐ TRÊN CỘT LƯỢNG KHÁCH ---
        org.jfree.chart.plot.CategoryPlot plotCust = customerChart.getCategoryPlot();
        org.jfree.chart.renderer.category.BarRenderer renCust = (org.jfree.chart.renderer.category.BarRenderer) plotCust.getRenderer();
        renCust.setDefaultItemLabelsVisible(true);
        renCust.setDefaultItemLabelGenerator(new org.jfree.chart.labels.StandardCategoryItemLabelGenerator(
                "{2}", new java.text.DecimalFormat("0")));
        plotCust.getRangeAxis().setUpperMargin(0.2); // Nới rộng đỉnh biểu đồ 20%

        formatChart(barChart, new Color(70, 130, 180));
        formatChart(customerChart, new Color(46, 204, 113));

        displayChartInPanel(jpnChartLeft, barChart);
        displayChartInPanel(jpnChartRight, customerChart);
    }

    private void displaySummary() {
        // 1. Gọi hàm lấy dữ liệu
        Double doanhThuThang = statRepo.getTotalRevenueMonth();
        Double doanhThuTuan = statRepo.getTotalRevenueWeek();

        // 2. Định dạng tiền tệ (Ví dụ: 1.000.000 VNĐ)
        java.text.DecimalFormat df = new java.text.DecimalFormat("#,###");

        // 3. Set dữ liệu lên TextField
        txtDoanhThuThang.setText(df.format(doanhThuThang) + " VNĐ");
        txtDoanhThuTuan.setText(df.format(doanhThuTuan) + " VNĐ");

        // 4. Chỉnh cho đẹp (Không cho sửa, căn lề phải)
        txtDoanhThuThang.setEditable(false);
        txtDoanhThuTuan.setEditable(false);
        txtDoanhThuThang.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDoanhThuTuan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    }

    private boolean isValidDate() {
        java.util.Date tuNgay = jdTuNgay.getDate();
        java.util.Date denNgay = jdDenNgay.getDate();
        java.util.Date hienTai = new java.util.Date(); // Ngày hôm nay

        if (tuNgay == null || denNgay == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng không để trống ngày!");
            return false;
        }

        if (tuNgay.after(denNgay)) {
            JOptionPane.showMessageDialog(this, "Lỗi: 'Từ Ngày' không được lớn hơn 'Đến Ngày'!");
            return false;
        }

        if (denNgay.after(hienTai)) {
            JOptionPane.showMessageDialog(this, "Cảnh báo: 'Đến Ngày' không được vượt quá ngày hiện tại!");
            return false;
        }

        return true;
    }

    // Thêm tham số JTable và tên file để dùng chung cho 3 Tab
    private void exportToExcel(javax.swing.JTable table, String defaultName) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn nơi lưu file thống kê");
        fileChooser.setSelectedFile(new File(defaultName + ".xlsx")); // Gợi ý tên file

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();
            if (!filePath.endsWith(".xlsx")) {
                filePath += ".xlsx";
            }

            try (Workbook workbook = new XSSFWorkbook()) {
                Sheet sheet = workbook.createSheet("Thong Ke Barber5AE");
                DefaultTableModel model = (DefaultTableModel) table.getModel();

                // --- 1. STYLE HEADER ---
                CellStyle headerStyle = workbook.createCellStyle();
                org.apache.poi.ss.usermodel.Font font = workbook.createFont();
                font.setBold(true);
                font.setFontHeightInPoints((short) 12);
                headerStyle.setFont(font);
                headerStyle.setAlignment(HorizontalAlignment.CENTER);
                headerStyle.setBorderBottom(BorderStyle.THIN); // Thêm viền cho đẹp

                // --- 2. TIÊU ĐỀ CỘT ---
                Row headerRow = sheet.createRow(0);
                for (int i = 0; i < model.getColumnCount(); i++) {
                    Cell cell = headerRow.createCell(i);
                    cell.setCellValue(model.getColumnName(i));
                    cell.setCellStyle(headerStyle);
                }

                // --- 3. ĐỔ DỮ LIỆU (XỬ LÝ SỐ THÔNG MINH) ---
                for (int i = 0; i < model.getRowCount(); i++) {
                    Row row = sheet.createRow(i + 1);
                    for (int j = 0; j < model.getColumnCount(); j++) {
                        Object value = model.getValueAt(i, j);
                        if (value != null) {
                            Cell cell = row.createCell(j);
                            String strValue = value.toString().trim();

                            // Xử lý loại bỏ "VNĐ" và dấu phẩy để ghi vào Excel dạng số (Numeric)
                            // Giúp người dùng có thể dùng hàm SUM trong Excel
                            String cleanValue = strValue.replaceAll("[^0-9?!\\.]", "");

                            if (!cleanValue.isEmpty() && strValue.contains("VNĐ")) {
                                try {
                                    cell.setCellValue(Double.parseDouble(cleanValue));
                                } catch (Exception e) {
                                    cell.setCellValue(strValue);
                                }
                            } else {
                                // Kiểm tra nếu là số thuần túy
                                try {
                                    cell.setCellValue(Double.parseDouble(strValue));
                                } catch (Exception e) {
                                    cell.setCellValue(strValue);
                                }
                            }
                        }
                    }
                }

                // --- 4. TỰ ĐỘNG GIÃN CỘT ---
                for (int i = 0; i < model.getColumnCount(); i++) {
                    sheet.autoSizeColumn(i);
                }

                // --- 5. GHI FILE ---
                try (FileOutputStream fileOut = new FileOutputStream(filePath)) {
                    workbook.write(fileOut);
                    JOptionPane.showMessageDialog(this, "Xuất file thành công!");
                }

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
            }
        }
    }

    //Tab Dịch Vụ
    private void loadDefaultServiceChart() {
        List<Object[]> data = statRepo.getServiceStatisticsDefault();
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        DefaultCategoryDataset barDataset = new DefaultCategoryDataset();
        DefaultTableModel model = (DefaultTableModel) tblDichVu.getModel();
        model.setRowCount(0);

        for (Object[] row : data) {
            String name = row[0].toString();
            int count = Integer.parseInt(row[1].toString());
            double total = Double.parseDouble(row[2].toString());
            model.addRow(new Object[]{name, count, String.format("%,.0f VNĐ", total), row[3]});

            pieDataset.setValue(name, count);
            barDataset.addValue(count, "Số lượt", name);
        }

        // Biểu đồ Tròn - Hiện phần trăm
        JFreeChart pieChart = ChartFactory.createPieChart("TỶ LỆ DỊCH VỤ", pieDataset, true, true, false);
        org.jfree.chart.plot.PiePlot plot = (org.jfree.chart.plot.PiePlot) pieChart.getPlot();
        plot.setLabelGenerator(new org.jfree.chart.labels.StandardPieSectionLabelGenerator("{0}: {1} ({2})",
                new java.text.DecimalFormat("#,###"), new java.text.DecimalFormat("0.0%")));

        // Biểu đồ Cột - Hiện số lượng
        JFreeChart barChart = ChartFactory.createBarChart("TẦN SUẤT SỬ DỤNG", "Dịch vụ", "Số lần", barDataset);
        CategoryPlot barPlot = barChart.getCategoryPlot();
        BarRenderer barRen = (BarRenderer) barPlot.getRenderer();
        barRen.setDefaultItemLabelsVisible(true);
        barRen.setDefaultItemLabelGenerator(new org.jfree.chart.labels.StandardCategoryItemLabelGenerator("{2}", new java.text.DecimalFormat("0")));
        barPlot.getRangeAxis().setUpperMargin(0.2);

        displayChartInPanel(jpnChartLeft1, pieChart);
        displayChartInPanel(jpnChartRight1, barChart);
    }

    private void searchByDateSer() {
        java.util.Date tuNgay = jdTuNgay1.getDate();
        java.util.Date denNgay = jdDenNgay1.getDate();

        DefaultTableModel model = (DefaultTableModel) tblDichVu.getModel();
        model.setRowCount(0);

        try {
            List<Object[]> data = statRepo.getServiceStatistics(tuNgay, denNgay);
            DefaultPieDataset pieDataset = new DefaultPieDataset();
            DefaultCategoryDataset barDataset = new DefaultCategoryDataset();

            for (Object[] row : data) {
                String tenDV = row[0].toString();
                int soLuot = Integer.parseInt(row[1].toString());
                double doanhThu = Double.parseDouble(row[2].toString());

                model.addRow(new Object[]{tenDV, soLuot, String.format("%,.0f VNĐ", doanhThu), row[3]});

                pieDataset.setValue(tenDV, soLuot);
                barDataset.addValue(doanhThu, "Doanh thu", tenDV);
            }

            // --- 1. CẬP NHẬT BIỂU ĐỒ TRÒN (Tỷ lệ %) ---
            JFreeChart pieChart = ChartFactory.createPieChart("TỶ LỆ DỊCH VỤ THEO GIAI ĐOẠN", pieDataset, true, true, false);
            org.jfree.chart.plot.PiePlot piePlot = (org.jfree.chart.plot.PiePlot) pieChart.getPlot();

            // Hiển thị dạng: Tên dịch vụ: Số lượt (Phần trăm %)
            piePlot.setLabelGenerator(new org.jfree.chart.labels.StandardPieSectionLabelGenerator(
                    "{0}: {1} lượt ({2})",
                    new java.text.DecimalFormat("#,###"),
                    new java.text.DecimalFormat("0.0%")));

            // --- 2. CẬP NHẬT BIỂU ĐỒ CỘT (Doanh thu số tiền) ---
            JFreeChart barChart = ChartFactory.createBarChart("DOANH THU DỊCH VỤ", "Dịch vụ", "VNĐ", barDataset);
            org.jfree.chart.plot.CategoryPlot barPlot = barChart.getCategoryPlot();
            org.jfree.chart.renderer.category.BarRenderer renderer = (org.jfree.chart.renderer.category.BarRenderer) barPlot.getRenderer();

            renderer.setDefaultItemLabelsVisible(true); // Hiện số trên cột
            renderer.setDefaultItemLabelGenerator(new org.jfree.chart.labels.StandardCategoryItemLabelGenerator(
                    "{2}", new java.text.DecimalFormat("#,###"))); // Định dạng tiền tệ
            barPlot.getRangeAxis().setUpperMargin(0.2); // Nới rộng đỉnh để không bị che số

            // --- 3. HIỂN THỊ LÊN PANEL ---
            displayChartInPanel(jpnChartLeft1, pieChart);
            displayChartInPanel(jpnChartRight1, barChart);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private boolean isValidDate1() {

        java.util.Date tuNgay = jdTuNgay1.getDate();
        java.util.Date denNgay = jdDenNgay1.getDate();
        java.util.Date hienTai = new java.util.Date(); // Ngày hôm nay

        if (tuNgay == null || denNgay == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng không để trống ngày!");
            return false;
        }

        if (tuNgay.after(denNgay)) {
            JOptionPane.showMessageDialog(this, "Lỗi: 'Từ Ngày' không được lớn hơn 'Đến Ngày'!");
            return false;
        }

        if (denNgay.after(hienTai)) {
            JOptionPane.showMessageDialog(this, "Cảnh báo: 'Đến Ngày' không được vượt quá ngày hiện tại!");
            return false;
        }

        return true;

    }
    //Tab Nhân Viên

    public void loadDefaultEmployeeChart() {
        // Đặt tiêu đề viền cho bảng
        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(
                "Bảng thống kê hiệu suất nhân viên trong 7 ngày gần nhất"
        ));

        DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
        model.setRowCount(0);

        try {
            List<Object[]> data = statRepo.getEmployeeStatisticsDefault();

            DefaultPieDataset pieDataset = new DefaultPieDataset();
            DefaultCategoryDataset barDataset = new DefaultCategoryDataset();

            for (Object[] row : data) {
                String name = (row[0] != null) ? row[0].toString() : "N/A";
                String position = (row[1] != null) ? row[1].toString() : "N/A";
                int count = (row[2] != null) ? Integer.parseInt(row[2].toString()) : 0;
                double revenue = (row[3] != null) ? Double.parseDouble(row[3].toString()) : 0.0;
                String status = (row[4] != null) ? row[4].toString() : "";

                // 1. Đổ vào bảng
                model.addRow(new Object[]{
                    name,
                    position,
                    count,
                    String.format("%,.0f VNĐ", revenue),
                    status
                });

                // 2. Đổ dữ liệu vào dataset
                pieDataset.setValue(name, count);
                barDataset.addValue(revenue, "Doanh thu", name);
            }

            // --- VẼ BIỂU ĐỒ TRÒN (HIỆN PHẦN TRĂM) ---
            JFreeChart pieChart = ChartFactory.createPieChart("TỶ LỆ KHỐI LƯỢNG CÔNG VIỆC 7 NGÀY", pieDataset, true, true, false);
            org.jfree.chart.plot.PiePlot piePlot = (org.jfree.chart.plot.PiePlot) pieChart.getPlot();
            piePlot.setLabelGenerator(new org.jfree.chart.labels.StandardPieSectionLabelGenerator(
                    "{0}: {2}", // Hiển thị: Tên nhân viên: 25%
                    new java.text.DecimalFormat("#,###"),
                    new java.text.DecimalFormat("0.0%")
            ));
            piePlot.setBackgroundPaint(java.awt.Color.WHITE);

            // --- VẼ BIỂU ĐỒ CỘT (HIỆN SỐ TIỀN & FIX TRỤC TUNG) ---
            JFreeChart barChart = ChartFactory.createBarChart("DOANH THU THEO NHÂN VIÊN 7 NGÀY", "Nhân viên", "VNĐ", barDataset);
            org.jfree.chart.plot.CategoryPlot categoryPlot = barChart.getCategoryPlot();
            org.jfree.chart.renderer.category.BarRenderer renderer = (org.jfree.chart.renderer.category.BarRenderer) categoryPlot.getRenderer();

            // Hiện số tiền trên đỉnh cột
            renderer.setDefaultItemLabelsVisible(true);
            renderer.setDefaultItemLabelGenerator(new org.jfree.chart.labels.StandardCategoryItemLabelGenerator(
                    "{2}", new java.text.DecimalFormat("#,###")));

            // Fix lỗi cột cao hơn trục tung (Tạo khoảng trống phía trên 20%)
            categoryPlot.getRangeAxis().setUpperMargin(0.2);
            categoryPlot.setBackgroundPaint(java.awt.Color.WHITE);

            // Hiển thị lên Panel
            displayChartInPanel(jpnChartLeft2, pieChart);
            displayChartInPanel(jpnChartRight2, barChart);
            
            jScrollPane3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu nhân viên!");
        }
    }

    private void settingCalendar() {
        // Đổi ngôn ngữ JDateChooser sang tiếng Việt
        Locale localeVN = new Locale("vi", "VN");
        jdTuNgay.setLocale(localeVN);
        jdDenNgay.setLocale(localeVN);

        // Nếu muốn hiển thị định dạng ngày kiểu Việt Nam (dd/MM/yyyy)
        jdTuNgay.setDateFormatString("dd/MM/yyyy");
        jdDenNgay.setDateFormatString("dd/MM/yyyy");
        // Không cho phép chọn ngày ở tương lai
        jdTuNgay.setMaxSelectableDate(new java.util.Date());
        jdDenNgay.setMaxSelectableDate(new java.util.Date());

        jdTuNgay1.setLocale(localeVN);
        jdDenNgay1.setLocale(localeVN);

        // Nếu muốn hiển thị định dạng ngày kiểu Việt Nam (dd/MM/yyyy)
        jdTuNgay1.setDateFormatString("dd/MM/yyyy");
        jdDenNgay1.setDateFormatString("dd/MM/yyyy");
        // Không cho phép chọn ngày ở tương lai
        jdTuNgay1.setMaxSelectableDate(new java.util.Date());
        jdDenNgay1.setMaxSelectableDate(new java.util.Date());

        jdTuNgay2.setLocale(localeVN);
        jdDenNgay2.setLocale(localeVN);

        // Nếu muốn hiển thị định dạng ngày kiểu Việt Nam (dd/MM/yyyy)
        jdTuNgay2.setDateFormatString("dd/MM/yyyy");
        jdDenNgay2.setDateFormatString("dd/MM/yyyy");
        // Không cho phép chọn ngày ở tương lai
        jdTuNgay2.setMaxSelectableDate(new java.util.Date());
        jdDenNgay2.setMaxSelectableDate(new java.util.Date());
    }

    private boolean isValidDate2() {

        java.util.Date tuNgay = jdTuNgay2.getDate();
        java.util.Date denNgay = jdDenNgay2.getDate();
        java.util.Date hienTai = new java.util.Date(); // Ngày hôm nay

        if (tuNgay == null || denNgay == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng không để trống ngày!");
            return false;
        }

        if (tuNgay.after(denNgay)) {
            JOptionPane.showMessageDialog(this, "Lỗi: 'Từ Ngày' không được lớn hơn 'Đến Ngày'!");
            return false;
        }

        if (denNgay.after(hienTai)) {
            JOptionPane.showMessageDialog(this, "Cảnh báo: 'Đến Ngày' không được vượt quá ngày hiện tại!");
            return false;
        }

        return true;

    }

    private void searchByDataEmp() {
        java.util.Date tuNgay = jdTuNgay2.getDate();
        java.util.Date denNgay = jdDenNgay2.getDate();

        DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
        model.setRowCount(0);

        try {
            List<Object[]> data = statRepo.getEmployeeStatisticsByDate(tuNgay, denNgay);

            DefaultPieDataset pieDataset = new DefaultPieDataset();
            DefaultCategoryDataset barDataset = new DefaultCategoryDataset();

            for (Object[] row : data) {
                // Kiểm tra từng cột để tránh lỗi NullPointerException
                String tenNV = (row[0] != null) ? row[0].toString() : "Không tên";
                String chucVu = (row[1] != null) ? row[1].toString() : "N/A";

                // Xử lý số lượt (row[2])
                int soLuot = 0;
                if (row[2] != null) {
                    try {
                        soLuot = Integer.parseInt(row[2].toString());
                    } catch (NumberFormatException e) {
                        soLuot = 0;
                    }
                }
                double doanhThu = 0;
                if (row[3] != null) {
                    try {
                        doanhThu = Double.parseDouble(row[3].toString());
                    } catch (NumberFormatException e) {
                        doanhThu = 0;
                    }
                }

                String trangThai = (row[4] != null) ? row[4].toString() : "N/A";

                // 1. Đổ dữ liệu vào bảng
                model.addRow(new Object[]{tenNV, chucVu, soLuot, String.format("%,.0f VNĐ", doanhThu), trangThai});

                // 2. Đổ dữ liệu vào dataset biểu đồ
                pieDataset.setValue(tenNV, soLuot);
                barDataset.addValue(doanhThu, "Doanh thu", tenNV);
            }

            // --- 3. CẬP NHẬT BIỂU ĐỒ TRÒN ---
            JFreeChart pieChart = ChartFactory.createPieChart("HIỆU SUẤT NHÂN VIÊN (LƯỢT KHÁCH)", pieDataset, true, true, false);
            org.jfree.chart.plot.PiePlot piePlot = (org.jfree.chart.plot.PiePlot) pieChart.getPlot();
            piePlot.setLabelGenerator(new org.jfree.chart.labels.StandardPieSectionLabelGenerator(
                    "{0}: {1} lượt ({2})",
                    new java.text.DecimalFormat("#,###"),
                    new java.text.DecimalFormat("0.0%")));

            // --- 4. CẬP NHẬT BIỂU ĐỒ CỘT ---
            JFreeChart barChart = ChartFactory.createBarChart("DOANH THU THEO NHÂN VIÊN", "Nhân viên", "VNĐ", barDataset);
            org.jfree.chart.plot.CategoryPlot barPlot = barChart.getCategoryPlot();
            org.jfree.chart.renderer.category.BarRenderer renderer = (org.jfree.chart.renderer.category.BarRenderer) barPlot.getRenderer();

            renderer.setDefaultItemLabelsVisible(true);
            renderer.setDefaultItemLabelGenerator(new org.jfree.chart.labels.StandardCategoryItemLabelGenerator(
                    "{2}", new java.text.DecimalFormat("#,###")));
            barPlot.getRangeAxis().setUpperMargin(0.2);

            // --- 5. HIỂN THỊ LÊN PANEL ---
            displayChartInPanel(jpnChartLeft2, pieChart);
            displayChartInPanel(jpnChartRight2, barChart);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi tìm kiếm dữ liệu nhân viên!");
        }
    }

}
