/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poly.barber.view;

import javax.swing.JOptionPane;
import poly.barber.entity.Account;
import poly.barber.service.AccountService;
import poly.barber.util.AuthUtil;
import poly.barber.util.Session;
import poly.barber.view.Dialog.ServiceJDialog;
import poly.barber.view.dialog.AccountJDialog;
import poly.barber.view.dialog.AppointmentJDialog;
import poly.barber.view.dialog.BarberJDialog;
import poly.barber.view.dialog.CustomerView;
import poly.barber.view.dialog.DiscountJdialog;
import poly.barber.view.dialog.EmployeeView;
import poly.barber.view.dialog.HistoryJdialog;
import poly.barber.view.dialog.InvoiceJDialog;
import poly.barber.view.dialog.LoginDialog;
import poly.barber.view.dialog.PaymentJDialog;
import poly.barber.view.dialog.SplashDialog;
import poly.barber.view.dialog.StatisticalJdialog2;

/**
 *
 * @author Admin
 */
public class Barber5AEJFrame extends javax.swing.JFrame {

    private Account currentUser;

    /**
     * Creates new form Barber5AEJFrame
     */
    public Barber5AEJFrame() {
        initComponents();
        setLocationRelativeTo(null);

        // ❗ ẨN MAIN TRƯỚC
        setVisible(false);

        // 🌟 Splash
        SplashDialog splash = new SplashDialog(this, true);
        splash.setVisible(true);

        // 🔐 Login
        LoginDialog login = new LoginDialog(this);
        login.setVisible(true);

        // ❌ Nếu không login thì thoát
        if (!login.isLoginSuccess()) {
            System.exit(0);
        }

        // ✅ Nếu login OK
        setUser(login.getAccount());

        // 👉 HIỆN MAIN SAU KHI LOGIN
        setVisible(true);
    }

    // 🟢 Gán user và phân quyền
    public void setUser(Account acc) {
        this.currentUser = acc;
        Session.user = acc; // 🔥 QUAN TRỌNG

        lblUser.setText("<html>Xin chào,<br>" 
        + acc.getUsername() + " (" + acc.getRoleName() + ")</html>");

        // ❌ reset toàn bộ trước
btnNhanVien.setEnabled(true);
btnbarber.setEnabled(true);
btngiamgia.setEnabled(true);
btnservice.setEnabled(true);
btnstatical.setEnabled(true);
btntaikhoan.setEnabled(true);

        // ================= PHÂN QUYỀN =================
if (AuthUtil.isAdmin(acc)) {
    btnNhanVien.setEnabled(true);
    btnbarber.setEnabled(true);
    btngiamgia.setEnabled(true);
    btnservice.setEnabled(true);
    btnstatical.setEnabled(true);
    btntaikhoan.setEnabled(true);
}
else if (AuthUtil.isManager(acc)) {
    btnNhanVien.setEnabled(true); // ❗ sửa
    btnbarber.setEnabled(true);
    btnservice.setEnabled(true); // ❗ chỉ admin
    btngiamgia.setEnabled(true);
    btnstatical.setEnabled(true);
    btntaikhoan.setEnabled(true);
}
else if (AuthUtil.isStaff(acc)) {
    // staff chỉ đặt lịch → disable hết
}
    }
//ktra login
private boolean requireLogin() {
    if (Session.user == null) {
        JOptionPane.showMessageDialog(this, "Bạn chưa đăng nhập!");
        return false;
    }
    return true;
}

private boolean denyIfNoPermission(boolean condition) {
    if (!requireLogin() || !condition) {
        JOptionPane.showMessageDialog(this, "Bạn không có quyền!");
        return true;
    }
    return false;
}

    // Mở dialog
    private void openDialog(javax.swing.JDialog dialog) {
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        btntaikhoan = new javax.swing.JButton();
        btnout1 = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnservice = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btngiamgia = new javax.swing.JButton();
        btnpayment = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnbarber = new javax.swing.JButton();
        btninvoice = new javax.swing.JButton();
        btnstatical = new javax.swing.JButton();
        btnhistory = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(51, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUser.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("USER");
        jPanel2.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 240, -1));

        btntaikhoan.setBackground(new java.awt.Color(0, 102, 153));
        btntaikhoan.setForeground(new java.awt.Color(255, 255, 255));
        btntaikhoan.setText("QUẢN LÝ TÀI KHOẢN");
        btntaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntaikhoanActionPerformed(evt);
            }
        });
        jPanel2.add(btntaikhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 250, 40));

        btnout1.setBackground(new java.awt.Color(0, 102, 153));
        btnout1.setForeground(new java.awt.Color(255, 255, 255));
        btnout1.setText("ĐĂNG XUẤT");
        btnout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnout1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, 250, 40));

        btnKhachHang.setBackground(new java.awt.Color(0, 102, 153));
        btnKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btnKhachHang.setText("QUẢN LÝ KHÁCH HÀNG");
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });
        jPanel2.add(btnKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 250, 40));

        btnservice.setBackground(new java.awt.Color(0, 102, 153));
        btnservice.setForeground(new java.awt.Color(255, 255, 255));
        btnservice.setText("QUẢN LÝ DỊCH VỤ");
        btnservice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnserviceActionPerformed(evt);
            }
        });
        jPanel2.add(btnservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 250, 40));

        btnNhanVien.setBackground(new java.awt.Color(0, 102, 153));
        btnNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanVien.setText("QUẢN LÝ NHÂN VIÊN");
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });
        jPanel2.add(btnNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 250, 40));

        btngiamgia.setBackground(new java.awt.Color(0, 102, 153));
        btngiamgia.setForeground(new java.awt.Color(255, 255, 255));
        btngiamgia.setText("QUẢN LÝ GIẢM GIÁ");
        btngiamgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngiamgiaActionPerformed(evt);
            }
        });
        jPanel2.add(btngiamgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 250, 40));

        btnpayment.setBackground(new java.awt.Color(0, 102, 153));
        btnpayment.setForeground(new java.awt.Color(255, 255, 255));
        btnpayment.setText("THANH TOÁN");
        btnpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaymentActionPerformed(evt);
            }
        });
        jPanel2.add(btnpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 250, 40));

        jButton3.setBackground(new java.awt.Color(0, 102, 153));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("ĐẶT LỊCH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 250, 40));

        btnbarber.setBackground(new java.awt.Color(0, 102, 153));
        btnbarber.setForeground(new java.awt.Color(255, 255, 255));
        btnbarber.setText("BARBER");
        btnbarber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbarberActionPerformed(evt);
            }
        });
        jPanel2.add(btnbarber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 250, 40));

        btninvoice.setBackground(new java.awt.Color(0, 102, 153));
        btninvoice.setForeground(new java.awt.Color(255, 255, 255));
        btninvoice.setText("HOÁ ĐƠN");
        btninvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninvoiceActionPerformed(evt);
            }
        });
        jPanel2.add(btninvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 250, 40));

        btnstatical.setBackground(new java.awt.Color(0, 102, 153));
        btnstatical.setForeground(new java.awt.Color(255, 255, 255));
        btnstatical.setText("THỐNG KÊ");
        btnstatical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstaticalActionPerformed(evt);
            }
        });
        jPanel2.add(btnstatical, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 250, 40));

        btnhistory.setBackground(new java.awt.Color(0, 102, 153));
        btnhistory.setForeground(new java.awt.Color(255, 255, 255));
        btnhistory.setText("LỊCH SỬ");
        btnhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhistoryActionPerformed(evt);
            }
        });
        jPanel2.add(btnhistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 250, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/Gemini_Generated_Image_f4l6m7f4l6m7f4l6.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 940));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/Gemini_Generated_Image_9kyc8n9kyc8n9kyc.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngiamgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngiamgiaActionPerformed
        // TODO add your handling code here:
    if (denyIfNoPermission(AuthUtil.canDiscount(Session.user))) return;

    DiscountJdialog d = new DiscountJdialog(this, true);
    d.setUser(currentUser);
    openDialog(d);
    }//GEN-LAST:event_btngiamgiaActionPerformed

    private void btnbarberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbarberActionPerformed
        // TODO add your handling code here:
    if (denyIfNoPermission(AuthUtil.canBarber(Session.user))) return;

    openDialog(new BarberJDialog(this, true));
    }//GEN-LAST:event_btnbarberActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
    if (denyIfNoPermission(AuthUtil.canEmployee(Session.user))) return;

    openDialog(new EmployeeView(this, true));
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        // TODO add your handling code here:
    if (denyIfNoPermission(AuthUtil.canCustomer(Session.user))) return;

    openDialog(new CustomerView(this, true,false)); //Tham số thứ 3 truyền vào để ẩn nút chọn khách hàng
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btninvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninvoiceActionPerformed
    if (denyIfNoPermission(AuthUtil.canInvoice(Session.user))) return;

    openDialog(new InvoiceJDialog(this, true));
    }//GEN-LAST:event_btninvoiceActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    if (denyIfNoPermission(AuthUtil.canAppointment(Session.user))) return;

    openDialog(new AppointmentJDialog(this, true));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnserviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnserviceActionPerformed
        // TODO add your handling code here:
    if (denyIfNoPermission(AuthUtil.canService(Session.user))) return;

    openDialog(new ServiceJDialog(this, true));
    }//GEN-LAST:event_btnserviceActionPerformed

    private void btnhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhistoryActionPerformed
        // TODO add your handling code here:
    if (denyIfNoPermission(AuthUtil.canHistory(Session.user))) return;

    openDialog(new HistoryJdialog(this, true));
    }//GEN-LAST:event_btnhistoryActionPerformed

    private void btnstaticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstaticalActionPerformed
        // TODO add your handling code here:
    if (denyIfNoPermission(AuthUtil.canStatistic(Session.user))) return;

    openDialog(new StatisticalJdialog2(this, true));
    }//GEN-LAST:event_btnstaticalActionPerformed

    private void btntaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntaikhoanActionPerformed
        // TODO add your handling code here:
    if (denyIfNoPermission(AuthUtil.canAccount(Session.user))) return;

    openDialog(new AccountJDialog(this, true));
    }//GEN-LAST:event_btntaikhoanActionPerformed

    private void btnpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaymentActionPerformed
        // TODO add your handling code here:
     if (denyIfNoPermission(AuthUtil.canPayment(Session.user))) return;

    PaymentJDialog d = new PaymentJDialog(this, true);
    d.setPaymentData("1", "500000");
    openDialog(d);
    }//GEN-LAST:event_btnpaymentActionPerformed

    private void btnout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnout1ActionPerformed
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc muốn đăng xuất?",
                "Xác nhận",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {

            // ❌ Xóa user hiện tại
            currentUser = null;

            // ❌ Ẩn main
            this.setVisible(false);

            // 🔐 Mở lại login
            LoginDialog login = new LoginDialog(this);
            login.setVisible(true);

            // ❌ Nếu không login lại → thoát
            if (!login.isLoginSuccess()) {
                System.exit(0);
            }

            // ✅ Nếu login lại thành công
            setUser(login.getAccount());

            // 👉 Hiện lại main
            this.setVisible(true);
        }
    }//GEN-LAST:event_btnout1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barber5AEJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barber5AEJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barber5AEJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barber5AEJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>

        /* Create and display the form */
        // 🌟 Splash
        java.awt.EventQueue.invokeLater(() -> new Barber5AEJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnbarber;
    private javax.swing.JButton btngiamgia;
    private javax.swing.JButton btnhistory;
    private javax.swing.JButton btninvoice;
    private javax.swing.JButton btnout1;
    private javax.swing.JButton btnpayment;
    private javax.swing.JButton btnservice;
    private javax.swing.JButton btnstatical;
    private javax.swing.JButton btntaikhoan;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
